### ISSUE TITLE
Prettier for code formatting.

### ISSUE THREAD

**Issue by ivikash** [PAIR-code/deeplearnjs#104]
Can we use `Prettier` https://github.com/prettier/prettier for code formatting? This will help us ensure the same formatting across different editors. A sample prettier config can be `prettier --list-different --print-width 80 --single-quote --no-semi --no-bracket-spacing`

Also, we can have this as a precommit hook and ensure that commits are well formatted.

**Comment by nsthorat** [comment]
I just submitted changes to get clang-format working with vscode. We prefer clang format as it adhere's to Google standard style guide.

**Comment by ivikash** [comment]
Will this be specific to `VSCode`? I keep switching between `emacs` and `WebStorm`, so I think something generic would be much more helpful plus prettier is quiet solid.

**Comment by nsthorat** [comment]
clang-format is very generic and widely supported. It also has a command line tool and plugins for most major IDEs (we just use "Google" as the style setting).

For jetbrains:
https://plugins.jetbrains.com/plugin/8396-clangformatij

**Comment by ivikash** [comment]
Thanks!
