### ISSUE TITLE
Feature Request: Support asymmetric kernel sizes in conv2d()

### ISSUE THREAD

**Issue by lukasadam** [PAIR-code/deeplearnjs#106]
Title is self-explainatory: Is there any way to get asymmetric (e.g. non-nxn) Kernels in the conv2d op?

**Comment by nsthorat** [comment]
This will be fixed today by https://github.com/PAIR-code/deeplearnjs/pull/67.

We'll be releasing 0.2.0 today once this PR is done (Daniel is writing unit tests now).
