### ISSUE TITLE
It's want open demo in desktop Chrome, when I opened it in desktop Chrome.

### ISSUE THREAD

**Issue by A077** [PAIR-code/deeplearnjs#12]
![image](https://user-images.githubusercontent.com/22576804/29003685-46b2c20a-7acc-11e7-869c-d68d555073d8.png)

How see a demo which can work only in desktop chrome, when it doesn't works on desktop chrome.

**Comment by dsmilkov** [comment]
Hi @A077,

If you can visit: http://webglreport.com/, this page will let you know if WebGL is supported on your device.

Additionally, you can visit chrome://settings/?search=hardware and check if 'Use hardware acceleration when available is checked' is checked.

If they are both ok, can you share some more details about your environment such as
- OS
- Chrome version
- GPU model

Thanks!

**Comment by A077** [comment]
The problem is in disabled hardware acceleration. Just enabled and it's work.

**Comment by A077** [comment]
The problem is in disabled hardware acceleration. Just enabled and it's work.
