### ISSUE TITLE
math.switchDimInternal() is showing "Not yet implemented!". How to transpose a matrix if switchDimInternal isn't implemented yet?

### ISSUE THREAD

**Issue by kailashahirwar** [PAIR-code/deeplearnjs#132]
Is there any other way to transpose a matrix in deeplearn?

**Comment by nsthorat** [comment]
Ah, so we have a CPU version of transpose, but haven't yet implemented it on the GPU.

If you're just trying to transpose weights, or something of that sort, you can do it with an explicit NDArrayMathCPU object, but if you need it on the GPU (for performance, transposition is part of your model or something) then it needs to be implemented properly on the GPU. If you want to send us a PR I can help you think about how to do that!
