### ISSUE TITLE
Problem doing the setup at the 'npm run prep' step

### ISSUE THREAD

**Issue by kaihuchen** [PAIR-code/deeplearnjs#14]
First I want to thank you for making deeplearn.js available. I have been waiting for such a GPU-capable js-based deep learning system since Karpathy's ConvNet.

While going through the Getting Started guide trying to set it up, I got stucked at the **npm run prep** step with the following errors:
<pre>
$ npm run prep

 deeplearn@0.1.0 prep /mnt/ml/tests/deeplearnjs
 npm install && bower install && mkdirp dist

npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deeplearn@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @types/lodash@4.14.71 (node_modules/@types/lodash):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: EEXIST: file already exists, mkdir '/mnt/ml/tests/deeplearnjs/node_modules/.staging/@types/lodash-321a893a/mapValues'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File exists: /mnt/ml/tests/deeplearnjs/node_modules/.staging/@types/lodash-321a893a/mapValues
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: remap-istanbul@0.8.4 (node_modules/remap-istanbul):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/mnt/ml/tests/deeplearnjs/node_modules/.staging/remap-istanbul-3e55a54e/tmp/remap-html-report-inline/support/inlinesource.ts.html'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: shelljs@0.7.8 (node_modules/shelljs):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chmod '/mnt/ml/tests/deeplearnjs/node_modules/.staging/shelljs-c180d202/src/grep.js'

npm ERR! path /mnt/ml/tests/deeplearnjs/node_modules/.staging/bower-30447fb7/lib/node_modules/ansi-regex/readme.md
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/mnt/ml/tests/deeplearnjs/node_modules/.staging/bower-30447fb7/lib/node_modules/ansi-regex/readme.md'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-08-06T18_26_43_676Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! deeplearn@0.1.0 prep: `npm install && bower install && mkdirp dist`
npm ERR! Exit status 254
npm ERR!
npm ERR! Failed at the deeplearn@0.1.0 prep script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-08-06T18_26_43_701Z-debug.log
</pre>

 I am doing this on a Ubuntu 14.04.5 LTS system, my node.js version is v8.2.1.
Please help.

**Comment by kaihuchen** [comment]
Turns out likely to be my own doing. Somehow the npm and bower installations on my system were kind of messed up.   

Issue closed.

**Comment by nsthorat** [comment]
Awesome, glad you found the fix.

Sorry we were late to getting to this, let us know if you have any more problems :)
