### ISSUE TITLE
Improve the "device is not supported message"

### ISSUE THREAD

**Issue by dsmilkov** [PAIR-code/deeplearnjs#16]
If the user is using Desktop Chrome, we should mention that they should check their settings for "Hardware acceleration". See #12 for an example of where this would have helped.

**Comment by ManrajGrover** [comment]
@dsmilkov Hi, I would like to take this one up and fix. I have the development environment setup and have signed the CLA. I believe we need to specifically check for WebGL being enabled after device support check and provide the solution shared [here](https://github.com/PAIR-code/deeplearnjs/issues/12#issuecomment-320516744). Code where changes need to be made is here:

https://github.com/PAIR-code/deeplearnjs/blob/master/demos/homepage/assets/support.js#L58
