### ISSUE TITLE
Correct way to share variables

### ISSUE THREAD

**Issue by reiinakano** [PAIR-code/deeplearnjs#168]
What is the correct way to share variables in deeplearnjs?

One way I think is to explicitly pass it around i.e.

```ts
const myVar = this.graph.variable('myvar', varianceInitializer.initialize([256, 784], 256, 784));

// First neural net
net1 = this.graph.matmul(net1, myVar);

// Second neural net sharing the same variable myVar
net2 = this.graph.matmul(net2, myVar);
```
(Please check if that was correct also)

Is there another way similar to Tensorflow's `reuse` parameter, perhaps checking first if the variable has the same name already in the graph, and reusing that instead?

I thought about doing something like this
```ts
this.graph.getNodes().filter((x) => x.name === 'myvar');
```

but this returns the `VariableNode` associated with `myVar` and I'm not sure how to retrieve the `Tensor` from it.

How would you guys do it?

**Comment by nsthorat** [comment]
Right now we just explicitly pass Variable Tensors around, this is definitely what I recommend. 

However, the approach with node filtering you provided will work. To get the Tensor just use ".output" on the VariableNode you get back!

**Comment by reiinakano** [comment]
Ah, I didn't know about `.output`. Thanks @nsthorat!
