### ISSUE TITLE
Migrate all shaders to logical sampling

### ISSUE THREAD

**Issue by dsmilkov** [PAIR-code/deeplearnjs#18]
Migrate all shaders to logical sampling once #9 is done.

This will make our shaders much easier to read/understand and opens up flexibility in how we encode/decode floats into textures, including the ability to pack floats into `gl.UNSIGNED_BYTE`s needed for Safari and iOS support.

**Comment by nsthorat** [comment]
One thing I want to note, we should migrate conv2d / pooling layers to use the TF-style padding when this happens (SAME | VALID).

**Comment by dsmilkov** [comment]
#40 migrated all binary ops.

**Comment by dsmilkov** [comment]
#54 finished moving all ops to logical. This resolves this issue
