### ISSUE TITLE
Ideas for contribution

### ISSUE THREAD

**Issue by chaosmail** [PAIR-code/deeplearnjs#186]
Hi guys,

First of all, thanks for the great work on this library; it looks amazing and like something I have been looking for since a couple of years!

I am the author of CaffeJS [1] (a hobby project during my Master program [2]) and would like to start contributing to deeplearn.js instead, which as of today looks like the most sophisticated DL library for the browser out there. Do you have any feature roadmap, meeting notes, etc available or are you working with github issues/feature requests only?

I will also give a talk at a Tech conference in Zurich about DL in the browser in a few weeks and would love to move my demos to deeplearn.js. Would this be ok for you? Are there any notes, anecdotes, timelines, release plans etc that I could share?

Thanks in advance!
All the best,
Christoph

[1] https://github.com/chaosmail/caffejs
[2] http://chaosmail.github.io/projects/

**Comment by nsthorat** [comment]
Hi Christoph,

Wow, awesome! We're definitely interested, and I think you moving demos to deeplearn.js would be a great idea, if you get deepdream working we'll feature it on the homepage (there's a little bit we need to do before this is possible, but not too much).

We've got an internal unofficial roadmap that we're trying to formalize for external contributors in the near future, but if you're considering contributing seriously maybe we can set up a sync over video chat and talk about what projects would make sense? Much higher throughput!

Let me know if video chat works for you, if not, no worries, we can talk here / over email.

**Comment by chaosmail** [comment]
Hi @nsthorat 
sounds great to me! I agree that it would be nice to have a short video chat; my email for hangouts is office [@] [github_username] [.at]. Could you shoot me a mail so we can agree on a time?
Best,
Christoph

**Comment by nsthorat** [comment]
Shot you an email, sorry about the delay.

Here are some issues / ideas that people could work on, I'll continue to add them with these labels: https://github.com/PAIR-code/deeplearnjs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
