### ISSUE TITLE
Automatic differentiation?

### ISSUE THREAD

**Issue by kevinrobinson** [PAIR-code/deeplearnjs#187]
From @nsthorat thread in https://github.com/PAIR-code/deeplearnjs/issues/33#issuecomment-333401000

> One thing I want to let you know is that we're going to change our high level differentiation API soon. No more Graphs / Sessions, we're going to be more like the pytorch define by run (we'll only have the NDArrayMath layer & auto differentiation). That being said, you can start building this out, but just make sure you have this in mind. The data API is probably going to change at some point soon as well (XHRDataset, etc).

> The graph / session model are horribly unintuitive, I agree. We only decided to go that route to mirror TensorFlow, but now we're regretting it since people have a hard time grasping it. The graph / session are also impossible to debug, even for those of us that wrote the original code. The new world will actually make stack traces sane.

An API change would be super interesting, especially for lowering the barrier for folks to experiment.  Is the idea a numpy-looking API that traces execution, or a compile-time pass to inject the tracing (to enable plain JS operators)?  I'd be interested in learning more about what you all are thinking, and seeing if there are pieces that I could help with prototyping, or pitch in with chipping away at implementation if you all already have a direction.

I imagine other folks might too.  Thanks!

**Comment by nsthorat** [comment]
Hi Kevin,

We're going to build an auto-grad mode soon. I'm going to write a design doc in the coming week. Most likely there will be pieces of it that will be great to get help with! As soon as we converge around the design we want to go with, I will update you with the thoughts.

We've been promising this for a while, but we're also going to be more concrete about which projects we think the OSS community would be perfect to help out with.

Is the autodiff stuff something you really want to work on - or are you looking for something in general? If looking for something in general, it would be helpful to think about where on the spectrum of library infrastructure <=> demos / frontend stuff you'd like to contribute; we have projects everywhere along that spectrum!

**Comment by kevinrobinson** [comment]
@nsthorat Cool, sounds good!

I'm interested in auto-grad in particular, but also understand a core API change like that is probably hard to do OSS-style.  I'll be interested when you're ready share or post more!

In general, I'm probably most interested in playing around with product applications and fun demos, but suspect that for most new ambitious things that will take some wrestling with performance at the library level too. :)

**Comment by dsmilkov** [comment]
Hi,

We [released 0.5.0](https://github.com/PAIR-code/deeplearnjs/releases/tag/v0.5.0) with new eager API which does auto-grad style differentiation. Hope you like it!
