### ISSUE TITLE
Add support for Safari and iOS

### ISSUE THREAD

**Issue by dsmilkov** [PAIR-code/deeplearnjs#19]
Safari and iOS don't fully support `OES_texture_float` extension, which means we can't write and read floats from textures.

The workaround is to use textures with `gl.UNSIGNED_BYTE` data type and encode/decode floats into 4 uint8 numbers ourselves.

For this to happen we need to migrate all of our shaders to logical sampling, tracked as #18.

**Comment by nsthorat** [comment]
Also, for iOS we need to use half floats. For now, I think this is okay, but we might want to consider packing two 16 bit floats in two channels (since with WebGL 1.0 we're already wasting that memory).

**Comment by jamesmcintyre** [comment]
@nsthorat @dsmilkov any idea on how much work/time is involved,?  I'm wondering if this library could be used via React Native on iOS.

**Comment by nsthorat** [comment]
We're in the process of rewriting our shaders to be a little big more generic so that we can abstract away the physical texture format, we expect this to be done within a few weeks (we're actively working on it).

**Comment by jamesmcintyre** [comment]
@nsthorat that's awesome, can't wait! thanks for the reply!

**Comment by iamblue** [comment]
Any roadmap or update  for this issue ?

thanks~

**Comment by nsthorat** [comment]
iOS now works at the library level!

The demos haven't been updated, but you should be able to use the library on iPhones now. Desktop Safari will work after one more small change.

**Comment by iamblue** [comment]
@nsthorat  got it ~ thanks ~

**Comment by nikcheerla** [comment]
What exactly does it mean that "while the library supports most devices, our demos don't currently work on iOS Mobile or Desktop Safari". If we write and develop code "normally" for the browser should it automatically work on iOS mobile, or are there any tweaks we have to make manually?

**Comment by nsthorat** [comment]
The demos have some issues with Polymer and sometimes the way we render to canvas on iOS Mobile / Desktop Safari. There's actually not much more work needed to get the demos working everywhere, we just haven't done it yet.

**Comment by dsmilkov** [comment]
Closing since our demos are already enabled on iOS devices.
