### ISSUE TITLE
Links please to some examples to load a simple Tensorflow RNN dataset

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#191]
Trying to load into deeplearnjs a Tensorflow V 1.0 dataset using the easiest RNN I can find at:

https://github.com/sherjilozair/char-rnn-tensorflow

1. Must I re-compile with the newest version of Tensorflow?
2. Can someone add links to any bare-bones examples of deeplearnjs loading datasets.

P.S. I am trying to convert a php python Tensorflow music playing website to deeplearnjs to remove the horrible server-client time lag on each submit

See working website at:

https://quick-test-rnn-rocksetta.c9users.io/index.php

A simple example dataset would be at: 

https://github.com/hpssjellis/char-rnn-tensorflow-music-3dprinting/tree/master/save-tinyshakespeare

**Comment by hpssjellis** [comment]
I think this LSTM might be what I am looking for


https://github.com/PAIR-code/deeplearnjs/tree/master/demos/lstm

**Comment by nsthorat** [comment]
Do you mean load the checkpoint weights themselves?

Check out the script [here](https://github.com/PAIR-code/deeplearnjs/blob/master/scripts/dump_checkpoint_vars.py), this will dump the weights from your checkpoint file into a set of files that can be ingested by our [CheckpointLoader](https://github.com/PAIR-code/deeplearnjs/blob/master/src/data/checkpoint_loader.ts)

We have a tutorial to help out with this [here](https://deeplearnjs.org/demos/mnist/mnist.html)

Hope this helps, let me know if there's something you need guidance with.

**Comment by hpssjellis** [comment]
Thanks @nsthorat I am finding a few examples. On second thought the entire character based RNN I am trying to do should be able to be trained and run fully in the browser. 

The input could simply be a textarea and the output to a textarea. As I mentioned here is the github of the original Tensorflow character rnn 

https://github.com/sherjilozair/char-rnn-tensorflow

If anyone knows of an example of a character rnn please reply.

**Comment by hpssjellis** [comment]
Thanks for the help
