### ISSUE TITLE
Graph is not defined

### ISSUE THREAD

**Issue by ChipiKaf** [PAIR-code/deeplearnjs#193]
I get the error 

> Uncaught ReferenceError: Graph is not defined

 in my chrome console when I try the training code in the introduction tutorial. In my HTML, deeplearn.js is included before my index.js. Here is a snippet of the code I am trying to run:

`const g = new Graph();
const inputShape = [3];
const input_tensor = g.placeholder('input', inputShape);

const label_shape = [1];
const label_tensor = g.placeholder('label', label_shape);
const multiplier = g.variable('multiplier', Array2D.randNormal([1, 3]));

const output_tensor = g.matmul(multiplier, input_tensor);
const cost_tensor = g.meanSquaredCost(output_tensor, label_tensor);

console.log(output_tensor.shape);
`

**Comment by reiinakano** [comment]
sorry for asking the obvious, but, did you import it? `import {Graph} from deeplearn`

**Comment by nsthorat** [comment]
Did @reiinakano's comment help?

**Comment by ChipiKaf** [comment]
Oops, how silly of me, I forgot to do the obvious. Thanks @reiinakano
