### ISSUE TITLE
Apache or Node server

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#205]
Once deeplearnjs is fully exported to a website I assume it will work on any webserver not just a nodejs server. Is that correct?

Sorry, someone has to ask the silly questions.

**Comment by reiinakano** [comment]
I think I can answer this. Yes, just have the webserver serve the contents of the `build` folder after building. The homepage will be the `.html` file that is generated, which will call the `bundle.js` file that is also generated.

**Comment by jsphweid** [comment]
It's native environment is the browser, actually. Just recently was a PR added so that it can even run on node without blowing up: https://github.com/PAIR-code/deeplearnjs/pull/155

**Comment by arthurjdam** [comment]
To expand on @jsphweid a little bit; it will run on any http-serving server. Ticket #155 refers more to running it headless on a NodeJS server entirely, without the need of a browser at all.
Whether you're sending out files through Apache, Nginx or Node (for example, Express), in any scenario the bundled deeplearn JS file gets sent to a client and all processing happens locally within their browser
