### ISSUE TITLE
How to determine the deeplearn version from javascript

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#211]
Been looking through the deeplearn API and Github code to find out how to dynamically show the active version (presently 0.3.0). If that can't be done then this is a request to allow javascript to show the active version. 

If the deeplearn version is stored can someone show me how to access it

My best guess so far is something like.
```
<script src="https://unpkg.com/deeplearn"></script>
<script>alert(deeplearn.appVersion)  </script>
```

**Comment by hpssjellis** [comment]
That would be great @Lewuathe, hopefully the javascript code would look like

 alert(deeplearn.version)

**Comment by Lewuathe** [comment]
@hpssjellis Exactly. You can refer the version in such a way. Please see [my example](https://github.com/PAIR-code/deeplearnjs/pull/212#issuecomment-336601166).

**Comment by nsthorat** [comment]
As of 0.3.2 you can use `deeplearn.version`. Feel free to close this issue if this is sufficient!

**Comment by hpssjellis** [comment]
` alert(deeplearn.version)  `

 works great! Thank you very much.
