### ISSUE TITLE
Full API reference

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#213]
Does anyone have a full API reference. The official one at 

http://deeplearnjs.org/docs/api/

does not have "Graph" or "Session" which are used in some of the examples.

**Comment by reiinakano** [comment]
These were present before, but I believe were removed in preparation for a bigger change in the training API. Graph and Session will be removed soon. See https://github.com/PAIR-code/deeplearnjs/issues/33#issuecomment-333401000

For now, you can look directly at the source code for graph https://github.com/PAIR-code/deeplearnjs/blob/master/src/graph/graph.ts and session https://github.com/PAIR-code/deeplearnjs/blob/master/src/graph/session.ts and just read the comments. In any case, the comments have the same information as whatever was in the documentation before it was removed.

**Comment by hpssjellis** [comment]
Thanks @reiinakano that makes sense, but will break any "Graph" and "Session" based examples. Hopefully a link to the new way of doing things can be posted here when it is active.

**Comment by nsthorat** [comment]
This was fixed by @Lewuathe, the docs should have the full API reference now:

https://deeplearnjs.org/docs/api/globals.html

Feel free to close this if this is sufficient!

**Comment by hpssjellis** [comment]
Thanks @Lewuathe
