### ISSUE TITLE
Dialog Polyfill v0.4.8 throws an error in Safari

### ISSUE THREAD

**Issue by ManrajGrover** [PAIR-code/deeplearnjs#215]
Currently, demos like `nn-art` and `model-builder` use `dialog-polyfill` `v0.4.8` which throws an error in `Safari Version 9.1.2 (11601.7.7)`.  However, it works as expected when `v0.4.9` is used. Demos need to be fixed for the same.

Error thrown:
```
[Error] TypeError: undefined is not an object (evaluating 'd.get')
	(anonymous function) (dialog-polyfill.min.js:1:9261)
	global code (dialog-polyfill.min.js:1:10436)
```

@nsthorat @dsmilkov I can take this one up.

**Comment by nsthorat** [comment]
This should be fixed now, right?

**Comment by ManrajGrover** [comment]
Yes @nsthorat, this can be closed now. 😄 I would love to contribute more and pick up other features that are on higher priority. If you could share some pointers, I can start working on those.
