### ISSUE TITLE
How do you transpose a matrix?

### ISSUE THREAD

**Issue by perborgen** [PAIR-code/deeplearnjs#216]
Does the library have an equivalent to Numpy's way of transposing matrices (matrix.T)?

**Comment by reiinakano** [comment]
Math.switchdim.

Or it might be math.transpose now.. I'm not sure which version the name change kicks in

**Comment by nsthorat** [comment]
It will be math.transpose after this PR is in:

https://github.com/PAIR-code/deeplearnjs/pull/167

Before this PR, you can use Math.switchDim, but this is only supported on a NDArrayMathCPU object. Once that PR is in, it will be available on the GPU.

**Comment by nsthorat** [comment]
`math.transpose` is now in. Feel free to close this issue if this is sufficient!
