### ISSUE TITLE
Your device is not yet supported

### ISSUE THREAD

**Issue by martin3000** [PAIR-code/deeplearnjs#222]
The page deeplearn.js tells me: "Your device is not yet supported, so we cannot show this demo. We are working hard on supporting more devices. For now, come back on desktop Chrome!"
But I have desktop chrome. Chrome 61.0.3163.100.
The problem ist the method of finding the WebGL context.
I found the following code for WebGL:
`    if (webglVersion === 2) {
        gl = canvas.getContext('webgl2', attributes);
    }
    else if (webglVersion === 1) {
        gl = (canvas.getContext('webgl', attributes) ||
            canvas.getContext('experimental-webgl', attributes));
    }`

The problem are the attributes. `canvas.getContext('webgl')` works, `canvas.getContext('webgl', attributes)`does not work.

**Comment by nsthorat** [comment]
Could you show us a screenshot of this page (both the WebGL 1.0 and the WebGL 2.0 tab)?

http://webglreport.com/

**Comment by martin3000** [comment]
![image](https://user-images.githubusercontent.com/21184101/31671908-5c1b3d3a-b35b-11e7-9552-374424255b0a.png)

![image](https://user-images.githubusercontent.com/21184101/31671941-6e435d30-b35b-11e7-8285-27620da5c003.png)

![image](https://user-images.githubusercontent.com/21184101/31671969-7f4702e4-b35b-11e7-9664-f92ab0f1e919.png)

![image](https://user-images.githubusercontent.com/21184101/31672004-964d2b26-b35b-11e7-8518-ecf80b9e3ab6.png)

**Comment by martin3000** [comment]
`Major Performance Caveat:  Yes` and the code requests `failIfMajorPerformanceCaveat: true`when building the attributes.

**Comment by nsthorat** [comment]
Ah, so it looks like it's probably a hardware issue. If you turn that off you might get software rendering of shaders, which might be unusably slow.

If you're able to build the code, can you turn that off and see what happens on your machine?

https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/webgl/gpgpu_util.ts#L31

**Comment by nsthorat** [comment]
Another question: do you have hardware acceleration enabled in chrome flags?

**Comment by martin3000** [comment]
After enabling this in chrome://flags it works now. Something was broken in the latest browser version. 2 weeks ago it was already working.
`Override software rendering list Mac, Windows, Linux, Chrome OS, Android
Overrides the built-in software rendering list and enables GPU-acceleration on unsupported system configurations. #ignore-gpu-blacklist
Enable`

**Comment by nsthorat** [comment]
Oh that's strange! Glad it's working now. Feel free to close this if you're comfortable with that solution!
