### ISSUE TITLE
Preprocessing in squeezenet demo

### ISSUE THREAD

**Issue by Dennitz** [PAIR-code/deeplearnjs#226]
What kind of preprocessing is done when infer() in the squeeznet demo is called?
Is it only subtracting the imagenet mean or are the RGB channels also changed to BGR somewhere? If not, is there a way to do this?

Thanks!

**Comment by nsthorat** [comment]
It's just subtracting out the imagenet mean. We're going to have a transpose operation on the GPU soon!

**Comment by reiinakano** [comment]
Wouldn't there already be gpu switchdim in 0.3.1 due to #195?

**Comment by nsthorat** [comment]
Ah yes, @reiinakano is right (he implemented it), you can use `switchDim`. @reiinakano++

We're going to rename it to transpose soon (but wont break `switchDim` calls).

**Comment by Dennitz** [comment]
Great, thanks!
