### ISSUE TITLE
Add functionality for SVD.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#245]
We can add this under a `linalg` file, just like numpy does.

See: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.svd.html

**Comment by haasdo95** [comment]
I'd like to have a try on this one...
But I'll have to review my numerical methods a little bit...

**Comment by dsmilkov** [comment]
Duplicate of #571
