### ISSUE TITLE
The git command performs an error

### ISSUE THREAD

**Issue by 601939654** [PAIR-code/deeplearnjs#25]
I can't execute the following command with git:
. / scripts/watch - demo demos/nn - art/nn - art. Ts
Error:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/.bin/watchify ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

What should I do?

**Comment by nsthorat** [comment]
Have you run `npm run prep`?

**Comment by 601939654** [comment]
It's already running.

**Comment by nsthorat** [comment]
It seems like you have an npm issue, did `npm run prep` give you errors?

**Comment by 601939654** [comment]
no errors at all

**Comment by 601939654** [comment]
Do I need to re-download and rerun?

**Comment by nsthorat** [comment]
What operating system are you on?

**Comment by 601939654** [comment]
window 10

**Comment by 601939654** [comment]
I've just tried it again, and I made the same mistake.

**Comment by nsthorat** [comment]
Ah, we haven't tried on windows.

Can you try editing this script:
https://github.com/PAIR-code/deeplearnjs/blob/master/scripts/watch-demo#L23

Change "node_modules/.bin/watchify" to "node_modules/.bin/watchify"

If that doesn't work, look in the node_modules/.bin directory and see what the watchify binary filename is and use that.

https://github.com/nodejs/node/issues/3675

We will check in a real fix.

**Comment by nsthorat** [comment]
@dsmilkov just letting you know this is an issue we should resolve.

**Comment by 601939654** [comment]
thank you so much,i try it at once.thanks again.

**Comment by 601939654** [comment]
Change "node_modules/.bin/watchify" to "node_modules/.bin/watchify"
The path is the same, right?

**Comment by dsmilkov** [comment]
Hi, I think the problem is that the path separator in windows is '\' which is different than linux '/'.

I just put a PR #28 that tries to fix this problem. In the mean time, can you checkout the `scripts-os` branch and see if the new changes work for you? Thanks!
