### ISSUE TITLE
Not able to run the "Getting started" example

### ISSUE THREAD

**Issue by cwhy** [PAIR-code/deeplearnjs#258]
I tried to compile the Typescript example on the front page, but encountered these error:
```shell
main.ts(11,13): error TS1308: 'await' expression is only allowed within an async function.
main.ts(11,26): error TS2341: Property 'data' is private and only accessible within class 'NDArray<T>'.
main.ts(14,8): error TS2341: Property 'data' is private and only accessible within class 'NDArray<T>'.
main.ts(18,20): error TS2339: Property 'dataSync' does not exist on type 'NDArray<"float32" | "int32" | "bool">'.
```
What I did:
```shell
npm init
npm install -g typescript
npm install deeplearn
```
* Create a file called `main.ts` contain all the contents of the example on the front page, which is:
```ts
import {Array1D, NDArrayMathGPU, Scalar} from 'deeplearn';

const math = new NDArrayMathGPU();
const a = Array1D.new([1, 2, 3]);
const b = Scalar.new(2);

const result = math.add(a, b);

// Option 1: With async/await.
// Caveat: in non-Chrome browsers you need to put this in an async function.
console.log(await result.data());  // Float32Array([3, 4, 5])

// Option 2: With a Promise.
result.data().then(data => console.log(data));

// Option 3: Synchronous download of data.
// This is simpler, but blocks the UI until the GPU is done.
console.log(result.dataSync());
```
```shell
tsc main.ts
```

If I did something wrong, what is the correct way to use deeplearn.js?

**Comment by nsthorat** [comment]
The first error about await comes from comment in Option 1 "// Caveat: in non-Chrome browsers you need to put this in an async function."

Option 1 will fail unless you wrap it in an async function:
`async function log() {
  console.log(await result.data());
}
`

This approach is best when you already have a larger app with async functions, otherwise in this case you should use Option 2.

The next 3 errors are because you're using an old copy of deeplearn, can you make sure you're using 0.3.3?

**Comment by dsmilkov** [comment]
Checkout also this started project I setup to help TypeScript users get a quick start:
https://github.com/dsmilkov/deeplearnjs-starter-typescript

**Comment by hpssjellis** [comment]
A reminder for anyone not wanting to learn typescript who wish to stick to normal javascript that I have a Github site setup with bare minimum examples on working web pages.

https://github.com/hpssjellis/deeplearnjs-javascript-examples

I am hoping to get much more examples, but may need some help converting basic demos from other libraries such as Tensorflow.

**Comment by cwhy** [comment]
Thank you all for your help, with the new version it works fine now.

**Comment by dsmilkov** [comment]
We added starter projects for both TypeScript and ES6 [here](https://github.com/PAIR-code/deeplearnjs/tree/master/starter) in our repo. See their `README.md` files for more details. Feel free to reopen if you run into issues.
