### ISSUE TITLE
Machine Learning Tutorials

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#279]
@dsmilkov

@nsthorat

I am launching a Kickstarter soon about making deeplearnjs tutorials for Machine Learning beginners.

I felt it was important to inform you before launch. The preview url is 

https://www.kickstarter.com/projects/rocksetta/641272504?ref=377286&token=1cf0f3c9

As advertisements should not go in github issues I will close this issue as soon as I have a sense that at least one of you has seen it.

**Comment by nsthorat** [comment]
Love the video :)

Would love more tutorials!

**Comment by hpssjellis** [comment]
Really fun to make the video instead of my normal boring teacher videos at https://www.youtube.com/user/keyfreemusic/videos

The Kickstarter should go live in the next few days. I would love to advertise here but do not feel that it is appropriate. As promised this issue is closed since you have seen it.
