### ISSUE TITLE
ES3/ES5 Javascript Usage in README not working

### ISSUE THREAD

**Issue by hma02** [PAIR-code/deeplearnjs#291]
Following the ES3/ES5 Javascript Usage in README, I just had a try with a simple website like below in my Chrome and get errors in my console.

```html
<html>
<head>
    <script src="https://unpkg.com/deeplearn@0.3.0"></script>
</head>
<body>
    <script>
    var dl = deeplearn;    // missing this line by the way
    var math = new dl.NDArrayMathGPU();
    var a = dl.Array1D.new([1, 2, 3]);
    var b = dl.Scalar.new(2);
    var result = math.add(a, b);
    
    // Option 1: With a Promise.
    result.data().then(data => console.log(data));

    // Option 2: Synchronous download of data. This is simpler, but blocks the UI.
    console.log(result.dataSync());

    </script>
</body>
</html>
```

my console gives:

```
Uncaught TypeError: result.data is not a function
    at (index):14
```

I think both Option 1 and 2 in this Usage instruction are wrong.

Because I list the properties of the object `result`:

```javascript
for(var propertyName in result) {console.log(typeof propertyName, propertyName)}
```

and there is no function named `data`  or `dataSync`.  I think for the Option 1, it should probably use `getValuesAsync` instead:

```
// Option 1: With a Promise.
result.getValuesAsync().then(data => console.log(data));
// Option 2: Synchronous download of data. This is simpler, but blocks the UI.
console.log(result.getValues());
```

**Comment by ManrajGrover** [comment]
@hma02 `data` and `dataSync` was added in version `0.3.3`. Please use this version or higher. You should change `0.3.0` to `0.3.3` or higher and try.

**Comment by allan5452** [comment]
Oh I see.  I just tried it works. Thanks a lot.

**Comment by hma02** [comment]
Ok It works now with `0.3.3`. Thanks
