### ISSUE TITLE
pure javascript  deeplearnjs examples

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#333]
I am trying to put together many simple snippets of deeplearnjs into some kind of high school curriculum. I am using my crowd curriculum database to organise it and get other peoples opinions (I made it a while ago so the concepts may be a bit old)

[http://rocksetta.com/crowd-curriculum/default.php?playlist=9](http://rocksetta.com/crowd-curriculum/default.php?playlist=9)

video at 

[https://www.youtube.com/watch?v=K1MmdGIMy-A](https://www.youtube.com/watch?v=K1MmdGIMy-A)

I don't want to bug Daniel Smilkov or Nikhil Thorat as they have much more difficult things to work on. 

The large demos on deeplearnjs are great and I can get lots of information from them, but I really want as simple as possible pure javascript examples of every possible deep learning algorithm.

Anyone interested in helping can contact me at

Twitter [@rocksetta](https://twitter.com/rocksetta)

Website [http://rocksetta.com/](http://rocksetta.com)

My main Github will be at 

[https://github.com/hpssjellis/deeplearnjs-javascript-examples](https://github.com/hpssjellis/deeplearnjs-javascript-examples)

or just comment in this thread.

**Comment by DiThi** [comment]
Your last link has the wrong text.

I'm very interested in your collection of examples, thank you.

**Comment by hpssjellis** [comment]
Good point. The link is broken. Will tidy it up when I get to a computer. The github is at

https://github.com/hpssjellis/deeplearnjs-javascript-examples

Presently having a hard time converting from typescript to javascript. Any help would be appreciated.

Would really like to break the model-builder into smaller javascript chunks. Each chunk showing one type of algorithm.

**Comment by hma02** [comment]
Hi @hpssjellis 
I'm basically working on the same thing, converting typescript into javascript. I just quickly made up a collection of some pure javascript demos I reproduced from deeplearnjs for self practice:

https://hma02.github.io/deeplearnjs-practice/

I have also included a convolution benchmark comparison between deeplearnjs and convnetjs.

**Comment by hpssjellis** [comment]
Those are great @hma02. Your code is nice and clean and much easier to understand than Typescript. I appreciate that your included scripts are not minified it makes it much easier to work with. 

Please keep making more demos. I am basically making a High School curriculum so your examples are still a bit advanced for my needs, but the more pure javascript deeplearnjs web sites out there the better.

**Comment by hma02** [comment]
Thanks @hpssjellis . As deeplearnjs guys recommended, I used VS code with some extensions to help lint and format. It has built in IntelliSense. I recommend it too if you haven't started using it.

**Comment by hpssjellis** [comment]
@hma02 You said the following:

>  It has built in IntelliSense for javascript.

I have been messing around with VS Code and the intelliSense for Typescript is amazing, but not finding anything worthwhile as intelliSense for Javascript. It kind of works, but only with classes and functions already declared on the page. Was that just a typo above or is there some trick to get VS Code with some kind of intelliSense for Javascript?

**Comment by hma02** [comment]
@hpssjellis 

The vscode websites describes their IntelliSense support. If you want to find it out exactly, you can find more information [here](https://code.visualstudio.com/docs/languages/javascript#_intellisense).

**Comment by hpssjellis** [comment]
IntelliSense for Javascript is all very new, late 2017. 

I do not have it working yet. If anyone has a list of steps to activate it that would be very helpful. Not sure if @hma02 has already got this working.

What I have done so far:

It uses the TS definition files that are already in the deeplearnjs project.

It needs a `jsconfig.json` file specific for deeplearnjs but I am not having much luck finding a working example. Useful link [here](https://code.visualstudio.com/docs/languages/jsconfig)

 VS code needs a preference changed from false to true (just override it in the spot available)
 file-->preferences--> settings  `    "javascript.implicitProjectConfig.checkJs": true`  

Installed the extension 
`JavaScript and TypeScript IntelliSense`

As I said it is not yet working for me with deeplearnjs but looks really interesting.

**Comment by hpssjellis** [comment]
Surprised how easy it was to get intellisense working with a different package using the hack above.

To load squeezenet intellisense I changed the package.json to include 

"dependencies": {

    "deeplearn": "~0.3.3",

    "deeplearn-squeezenet": "~0.1.2" 

  },

**Comment by hpssjellis** [comment]
I made a youtube video about using VS code for working with javascript and Intellisense but not having to worry about learning Typescript or ES6. Hope it helps someone.




https://youtu.be/aq4JByHZt9E


[![Instructional video](http://img.youtube.com/vi/aq4JByHZt9E/0.jpg)](https://youtu.be/aq4JByHZt9E)


The github is at https://github.com/hpssjellis/javascript-with-vscode-intellisense-no-ES6-no-Typescript

**Comment by QuantumInformation** [comment]
I'll be working on a video soon.

**Comment by hpssjellis** [comment]
@QuantumInformation Is your video about the above post or some easy pure Javascript examples of deeplearnjs?

Either way, what is your youtube videos link?

**Comment by QuantumInformation** [comment]
Deep learn in general https://www.youtube.com/channel/UC0XiDgtbFR8ohoGlstuFgGQ

**Comment by hpssjellis** [comment]
Not sure why, probably to reach a larger number of computers, but deeplearnjs transpiles to ES5 format. I have had a very difficult time converting the bundle.js file into regular old fashioned javascript.

Yesterday found out about 

`tsc --target ESNext   myTypeScriptFile.ts`

which could also be


`tsc --target ES2017   myTypeScriptFile.ts`



I can transpile each individual .ts file into a format that is almost pure javascript. You just have to go through and delete the "import" line and the keyword "export" before each function.



Anyone know a TSC command line statement to not generate the import and export commands? That would be really useful.

Here is an example Javascript generated file from Typescript using the above command. Really easy to delete the import line and put a script src tag in the html file and then just delete the "export" before the regular function command 

`import * as dl from 'deeplearn';
const math = dl.ENV.math;

export function isTraining() {
    statusElement.innerText = 'Training...';
}`

**Comment by erikwilson** [comment]
@hpssjellis sorry if I am missing the question, I haven't actually tried it myself but I'm curious if the default target of ES3 or explicitly setting it as ES5 might be what you are after.

**Comment by hpssjellis** [comment]
@erikwilson    ES5 is the default setting on the deeplearnjs tsconfig.json file. It creates a really messy file output that is needed for ES5 to deal with Async commands.

Setting the tsconfig.json file to ES2017 or ESNext is a much cleaner output but it still has import and export  commands that need to be deleted.

All is good. I am making do with what I have.

Check out the "mnist_eager" shown in  pure javascript at

https://hpssjellis.github.io/deeplearnjs-javascript-examples/jj07-mnist.html

**Comment by hpssjellis** [comment]
I think this situation can be closed now
