### ISSUE TITLE
Does deeplearnjs have a method to take the inverse of a matrix?

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#366]
Trying to duplicate this excellent matrix [Real Life Example](http://www.mathsisfun.com/algebra/matrix-inverse.html) Look 1/2 way down the page. The Bus and Train example.

I find it strange that deeplearnjs does not have an inverse method (Is it called something else?)
Is the inverse of a matrix something that is not used much in Machine Learning?

A permanent link to my github code showing my solution is [here](https://github.com/hpssjellis/deeplearnjs-javascript-examples/blob/2f9cda480e8c3c4298cc6d2d7f612cd3c6df1ee1/a03-matrix-math.html#L31-L32) 

I will try to write my code as a function.

**Comment by reiinakano** [comment]
Related #244. For what it's worth I haven't seen it used in neural networks, might be used a lot in other ML algorithms though

**Comment by hpssjellis** [comment]
Thanks @reiinakano I have got to start searching the other issues before posting.

**Comment by hpssjellis** [comment]
Solved my issue at 

[https://hpssjellis.github.io/deeplearnjs-javascript-examples/a03-matrix-math.html](https://hpssjellis.github.io/deeplearnjs-javascript-examples/a03-matrix-math.html)
