### ISSUE TITLE
Error in dumping weights from Pytorch model

### ISSUE THREAD

**Issue by mishra-avinash** [PAIR-code/deeplearnjs#370]
I used pytorch dumpers and faced few problems, i am listing them down with the solution .

1. I am using **../scripts/pytorch_checkpoint_dumper.py** to dump my weights from pytorch model. But i 
    am getting below error 
   `AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'` this error is coming from the 
    function **build_and_dump_vars**
    `for var_name, var_weights in self.state_dictionary.iteritems():` in file 
    **pytorch_checkpoint_dumper.py** .
    To resolve this i had to replace **self.state_dictionary.iteritems()** by **self.state_dictionary.items()**

2.  In file **../scripts/pytorch_checkpoint_dumper.py**  in function **build_and_dump_vars** i was 
      getting  **serializable error with map** so i had to replace line 
      `var_shape = map(int, list(var_weights.size()))`  by  
      `var_shape = list(map(int, list(var_weights.size())))`

3.   In file **../scripts/pytorch_checkpoint_dumper.py**  in function **build_and_dump_vars**
       i had to convert cuda tensors to cpu tensors by replacing the line 
       `tensor = var_weights.numpy()` by ` tensor = var_weights.cpu().numpy()`

My system configuration is : 

- Python : 3.6.2

- Cuda: V 8.0.61
- DeepLearnjs : 0.3.11
- Pytorch : 0.2.0_4

Let me know you want to know more how to produce these errors.

**Comment by ManrajGrover** [comment]
@mishra-avinash Hi! Thanks for opening this issue. These scripts were written in Python 2 and some of these features are not available in Python 3. Perhaps we should make it compatible with both Python 2 and Python 3. I'll send a PR soon for the same!
