### ISSUE TITLE
how to save a weights

### ISSUE THREAD

**Issue by husseinabed** [PAIR-code/deeplearnjs#385]
is there a way to save and load a weghits

**Comment by erikwilson** [comment]
Hopefully something more official will come out soon, but I just published on npm my own solution for serializing and deserializing graphs for others to use: 
https://www.npmjs.com/package/deeplearn-graph-serializer

**Comment by hma02** [comment]
@husseinabed 
I have implemented a way of downloading and loading weights in pure javascript ES3/ES5. See it in the [GAN demo](https://hma02.github.io/deeplearnjs-practice/deeplearn_gan.html)

**Comment by husseinabed** [comment]
thanks guys that was very helpfull :)

**Comment by nsthorat** [comment]
Nice work everyone!

We will provide an official way of doing this soon. We are working hard on a new API as well as eager mode, once that solidifies we will be removing the Graph entirely and provide an official way of exporting weights :)

**Comment by QuantumInformation** [comment]
Good work guys
