### ISSUE TITLE
Make it clear in the intro.md which devices are supported by the library

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#39]
Maybe make this a table (and make it clear what's not supported for the demos and what's not supported for the library).

We could maybe also give a rough timeline for each new platform / device combo since we're asked this a lot.

**Comment by dsmilkov** [comment]
Closing since we support the 3 major browsers (Chrome, Firefox, Safari) and the 2 major devices (Android, iOS)
