### ISSUE TITLE
Question: Tensorflow checkpoint reader integration

### ISSUE THREAD

**Issue by MarkusBordihn** [PAIR-code/deeplearnjs#407]
I currently working on an pure JavaScript based Tensorflow checkpoint loader, which doesn't need the Python script.

I tried to put the loader in an separate npm package, but unfortunately this is not working as expected (causing index signatures errors) because of the custom ndarray implementation used by deeplearnjs.

To avoid this errors I see the following solutions:
1. Creating a file 'deeplearnjs/src/data/tensorflow_loader.ts' which handles only the conversion of the data to the needed ndarray to avoid the signature errors. All the other logic is separate in an extra npm package, so the file would be only some lines long and should not need regular updates.
2. Only returning the data and let it up to the user to do the conversion in their custom code to the needed ndarray.
3. Your are proving an kind of data loader API which is handling the conversion and could be used for such cases.

I would prefer solution 1. to make it easier for the user to load such files out of the box.

Please let me know if you agree or if you prefer another solution.

Thanks.

**Comment by ManrajGrover** [comment]
Hi @MarkusBordihn, I love the idea of providing an out of box API for loading Tensorflow checkpoints but I do have a concern. Writing a checkpoint loader for a framework would require keeping it up to date with the latest developments in that framework, which requires a lot of maintenance.

**Comment by nsthorat** [comment]
+1 to @ManrajGrover. We're going to provide an official way to do TensorFlow => deeplearn.js in the near term future which will be optimal in terms of parse time / network size. I want to stay way from parsing the checkpoint itself in JavaScript, though I think in generate it could be a useful tool for others who don't want to run a script to dump the model.

Maybe you could create a separate repo that depends on deeplearn.js?

**Comment by MarkusBordihn** [comment]
Thanks for the feedback, I created a separate repro and just released the first version of the basic JavaScript based TensorFlow reader under https://github.com/google/deeplearn-tensorflow .

An detail demo instruction is available under:
https://github.com/google/deeplearn-tensorflow/blob/master/DEMO.md

**Comment by MarkusBordihn** [comment]
Hi Nikhil,
as explained more in detail per email. Feel free to take over the GitHub repro and the NPMjs name as soon your official integration is ready to use. Thanks.

**Comment by nkreeger** [comment]
Hi Markus,

I think we might put the official integration under `tensorflow/` - so having both a repo under `google/` might be confusing to some users. Do you mind moving it over to a personal repo?

Thanks!
Nick

**Comment by QuantumInformation** [comment]
Good work on official integration google!
