### ISSUE TITLE
Pad operation support in NDArray.

### ISSUE THREAD

**Issue by nkreeger** [PAIR-code/deeplearnjs#409]
Padding would be a great feature for NDArray. If you look at both NumPy and the TensorFlow docs - it is a non-trivial implementation.

**Comment by silky** [comment]
agreed

**Comment by dsmilkov** [comment]
Pad for 1D and 2D added in #531 thanks to @nkreeger !

**Comment by silky** [comment]
i'm keen on 4d, so can we re-open? :)
