### ISSUE TITLE
Problem in randTruncatedNormal

### ISSUE THREAD

**Issue by minsukkahng** [PAIR-code/deeplearnjs#415]
Hi Nikhil and nkreeger,

Looks like there is a problem in randTruncatedNormal. You know it is often used for initializing weights, but I don't think the initialization works properly now.  I'm not sure, but it may produce zeros. I think it came from one of the commits occurred between Nov 25 and Dec 4.

You can see this problem in the model-builder demo (https://deeplearnjs.org/demos/model-builder/). Look at the inference panel before you click the training button. It used to produce some random class probabilities (around 10-25% for top 3), but in the current demo, all the class probabilities are exactly 10.0%. which could not happen if weights are randomly initialized. When I replace randTruncatedNormal with randNormal, it works (producing probabilities around 10-25%).

I hope you can resolve this problem.

Cheers,
Minsuk (Brian) Kahng

**Comment by nkreeger** [comment]
Hi Minsuk,

I tweaked randTruncatedNormal to generate some better seeding data and match the TF API here:

https://www.tensorflow.org/api_docs/python/tf/truncated_normal

The one key takeaway is this part: "The generated values follow a normal distribution with specified mean and standard deviation, except that values whose magnitude is more than 2 standard deviations from the mean are dropped and re-picked."

When a random object is initialized, I find the upper and lower boundaries that are 2-standard deviations from the mean. If the randomization should be truncated, I use those protections and re-pick:
https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/rand.ts#L97

I added a simple log to layer_builder.ts:240 to dump the outputs of the randomization:
![screenshot from 2017-12-05 08-20-56](https://user-images.githubusercontent.com/306276/33617849-1a7c817c-d99e-11e7-8036-3de26700dc3d.png)

Looks like the values are close. I'll try and looking at the ported TF code to see if something doesn't match up. Could be a rounding issue at that precision in the UI.

**Comment by minsukkahng** [comment]
Thanks Nick for your kind reply. I hope you can easily fix it.

Cheers,
Minsuk (Brian) Kahng

**Comment by hma02** [comment]
The issue seems started with deeplearn@0.3.13

Using deeplearn@0.3.12 works fine for me on the ES5/ES3 side.

**Comment by nkreeger** [comment]
Should be fixed when https://github.com/PAIR-code/deeplearnjs/pull/434 lands.

**Comment by minsukkahng** [comment]
Thank you for the follow-up!
