### ISSUE TITLE
npm run prep   ERROR

### ISSUE THREAD

**Issue by lyrabbit** [PAIR-code/deeplearnjs#42]
npm run prep

ERROR:
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467

npm ERR! Linux 3.10.0-514.6.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-17851-1300de0c/registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm ERR! Expected: 55dbebef0ad9155382d9e9d3e497c1372345b44a
npm ERR! Actual:   806b428d361ea6047b4712064b88d709b0559e11
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /deeplearn/deeplearnjs/npm-debug.log

npm ERR! Linux 3.10.0-514.6.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "prep" "set" "registry" "https://registry.npm.taobao.org"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! deeplearn@0.1.0 prep: `npm install && bower install && mkdirp dist "set" "registry" "https://registry.npm.taobao.org"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deeplearn@0.1.0 prep script 'npm install && bower install && mkdirp dist "set" "registry" "https://registry.npm.taobao.org"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deeplearn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && bower install && mkdirp dist "set" "registry" "https://registry.npm.taobao.org"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deeplearn
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deeplearn
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /deeplearn/deeplearnjs/npm-debug.log

My operating system is centos7

Please Help！

**Comment by anna-mo** [comment]
probably u should check the installation of your node and npm

**Comment by nsthorat** [comment]
Looks like a problem with npm & bower, please check your installations and common npm problems (not a problem with our library, so closing this).

**Comment by dsmilkov** [comment]
Hi @lyrabbit,

Looks like the checksum failed for `bower-1.8.0.tgz`, which is very unusual. Can you try to re-install: 
```
rm -r node_modules/
npm install
````

Also try updating your node version. Lastly, any chance you are behind a firewall?

Thanks!

**Comment by dsmilkov** [comment]
Any luck in getting npm to work? Thanks!

**Comment by nsthorat** [comment]
Going to close this for inactivity, feel free to reopen :)
