### ISSUE TITLE
Update API documentation for 0.3.14

### ISSUE THREAD

**Issue by tmcw** [PAIR-code/deeplearnjs#439]
Yay, new release! Unfortunately, the [API docs](https://deeplearnjs.org/docs/api/index.html) are based on 72295cf, so they still advertise functionality like `.inGPU()` for `NDArray` objects.

**Comment by nsthorat** [comment]
Documentation should be updated now. That API change should be fairly contained (which is why we allowed it in a non major version released) - it was only used for tests in our world.

Thanks for the note!

**Comment by ManrajGrover** [comment]
This looks resolved and can be closed.

**Comment by nsthorat** [comment]
Docs are brand new and more manually curated! Hopefully this helps.

https://deeplearnjs.org/docs/api/
