### ISSUE TITLE
Bit sluggish performance when using GPU

### ISSUE THREAD

**Issue by ksachdeva** [PAIR-code/deeplearnjs#443]
Hi,

As part of learning the deeplearnjs example, I created a small sample (really small data set) and using simple linear regression.

Here is the link to the working version of the demo -
https://ksachdeva.github.io/deeplearn-examples/#/samples/tip-predictor

Here is the link to the github repo -
https://github.com/ksachdeva/deeplearn-examples/tree/master/webapp

Here is the link to the file which has the main guts vis-a-vis deeplearnjs -
https://github.com/ksachdeva/deeplearn-examples/blob/master/webapp/src/app/samples/tip-predictor/tip-predictor.service.ts

Here is a video showing the issue -
https://www.screencast.com/t/KM7O0Pn8

In order to see the problem please peform following steps -

* Use Chrome (I have not tried any other browser .. I am using Chrome 62 on OS X Sierra)
* Go to https://ksachdeva.github.io/deeplearn-examples/#/samples/tip-predictor
* Open Developer Console so that you can see the console.log
* Make sure CPU is selected
* Click on train
* You should see that the execution is pretty fast. Click on the clear button in javascript console
* Now select the GPU
* Click on train.

You will notice that with GPU option, the execution is slower. 

Once it is done then click on clear button in javascript console and it takes a while to clear up. 

Most likely I am going something wrong here as normally the performance with GPU option should be better.

Please suggest what may be wrong.

Regards
Kapil

**Comment by nsthorat** [comment]
Hi Kapil,

The reason you don't see huge speed improvements on the GPU is because your activations are quite small (scalars) - we parallelize over the size of the output NDArray. You get huge wins if you can vectorize your logic (batch the inputs so you are utilizing the GPU more).

Hope this helps.

**Comment by ksachdeva** [comment]
Thanks @nsthorat
