### ISSUE TITLE
can't start demos

### ISSUE THREAD

**Issue by adhaamehab** [PAIR-code/deeplearnjs#45]
Can't start demos with Desktop chrome last version while demos says : "This device is not yet supported please try to load this demo on a desktop computer with Chrome".

**Comment by dsmilkov** [comment]
Sorry about that. Can you give us more details such as:
 - Operating system
 - Chrome version
 - Machine type: laptop/desktop/tablet

Thanks!

**Comment by adhaamehab** [comment]
OS
> Windows 7 Ultimate service pack 1

Chrome Version Version 
> 60.0.3112.90 (Official Build) (64-bit)

Machine Type

> Desktop Intel Processor 64-bit

**Comment by nsthorat** [comment]
Can you check your chrome settings for "use hardware acceleration when available", and make sure that is on?

**Comment by adhaamehab** [comment]
I'm sorry for late reply
I checked this Options and it's turned ON

**Comment by mattmeye** [comment]
+1

> Operating system
win 10 pro
> Chrome version
Version 60.0.3112.90
> Machine type: laptop/desktop/tablet
desktop
> use hardware acceleration when available
on

**Comment by Swissbite** [comment]
Not working here:
- Win 10 Pro
- Version 60.0.3112.101 (Official Build) (64-bit)
- Laptop
- Hardware Acceleation: on

**Comment by derappelt** [comment]
Also not working.

- macOS 10.12.6
- Version 60.0.3112.101 (Official Build) (64-bit)
- MacBook Pro (13-inch, Early 2011)
- Hardware Acceleation: on

**Comment by dsmilkov** [comment]
Do you guys have a browser extension installed that hides the user agent by any chance?

To give on update on our side: we are working actively towards turning off the user agent checking and instead detect browser features.

**Comment by dsmilkov** [comment]
Related to this issue is #51 where the library works fully on Firefox, but we haven't enabled it yet due to problems with Polymer (not our library). Also working actively to fix this.

**Comment by davmillar** [comment]
Same on desktop computer running Fedora 25 with Chrome Version 60.0.3112.78 (Official Build) (64-bit), tried with both hardware acceleration off and on. My navigator.userAgent is "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

**Comment by nsthorat** [comment]
Hm, I spoofed that useragent and I get the demos.

Could everybody who has a problem send me:
userAgent
Whether this page says WebGL is supported: https://get.webgl.org/

**Comment by adhaamehab** [comment]
According to : [This](whoishostingthis.com/tools/user-agent/)
This is my useragent 

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

and yes the pages says that WebGL is supported

**Comment by dsmilkov** [comment]
Closing this issue since we are no longer spoofing the user agent, but testing for browser features instead. Reopen if the issue is still there.
