### ISSUE TITLE
Using SqueezeNet on ES6 fails

### ISSUE THREAD

**Issue by Samuelfaure** [PAIR-code/deeplearnjs#451]
I'm very interested in this library and image recognition possibilities of deeplearning.
Using Vue.js2 and ES6, I'm trying to reproduce the [squeezenet cat-demo](https://deeplearnjs.org/demos/playground/index.html#3429649a8ea4e1437a30a0a256c40708) but fail to do so.

Here is my component code: `this.$refs.toAnalyse` point to the cat picture on the DOM =>
```javascript
        import { NDArrayMathGPU } from 'deeplearn'
        import { SqueezeNet } from 'deeplearn-squeezenet'

        export default {
          name: 'HomePage',
          methods: {
            executeAnalyse () {
              const imgToAnalyse = this.$refs.toAnalyse

              const math = new NDArrayMathGPU()
              const squeezeNet = new SqueezeNet(math) // Line throwing the error
            }
          }
        }
```
This results in the following error : `Uncaught TypeError: deeplearn_1.initializeGPU is not a function`

In (unrelated?) news, it seems like the live demo linked earlier on the deeplearn.js website is not working anymore (also throws a TypeError: `TypeError: Cannot read property 'texShape' of undefined`). It used to work on my computer when I first tried it about a month ago.

Thank you very much for any help.

**Comment by Samuelfaure** [comment]
Btw I digged the issue quite some time, I can't find any information except that it probably comes from the deeplearn-squeezenet library :

```javascript
Object.defineProperty(exports, "__esModule", { value: true });
var deeplearn_1 = require("deeplearn");
// code omitted
var SqueezeNet = (function () {
    function SqueezeNet(math) {
        this.math = math;
        this.preprocessOffset = deeplearn_1.Array1D.new([103.939, 116.779, 123.68]);
        deeplearn_1.initializeGPU(this.math.getGPGPUContext(), this.math.getTextureManager()); // this line might be the culprit
    }
// lots of code omitted
```

**Comment by chaosmail** [comment]
Seems like the same problem as #445. From what I saw there are a lot of changes going on generalising the math backends at the moment.
I would recommend to checkout version 0.13.2 if you want to play around a bit before this gets fixed

**Comment by Samuelfaure** [comment]
@chaosmail Thank you for the answer. Do you mean version 0.3.12 ?

**Comment by chaosmail** [comment]
Yeah exactly, sorry about that!

**Comment by Samuelfaure** [comment]
Was able to make it work indeed with version 0.3.12, thanks!
