### ISSUE TITLE
v0.3.12 and v0.3.13 performs differently

### ISSUE THREAD

**Issue by rwieruch** [PAIR-code/deeplearnjs#452]
When I upgraded my project to 0.3.13 today, the neural network wasn't performing anymore. Did something change in between both versions? You can find my project [here](https://github.com/javascript-machine-learning/mnist-neural-network-deeplearnjs) and change the deeplearn version in the package.json file.

0.3.12

![deeplearn12](https://user-images.githubusercontent.com/2479967/34068628-81be0b4c-e279-11e7-8b03-c60790c8c2ae.gif)

0.3.13

![deeplearn13](https://user-images.githubusercontent.com/2479967/34068629-83510630-e279-11e7-92b5-5473c99f19a3.gif)

Maybe 0.3.14 fixes this issue. But I couldn't test it, because there I ran into a different bug seen in https://github.com/PAIR-code/deeplearnjs/issues/440

**Comment by nkreeger** [comment]
Try upgrading to 0.3.14 - there was a bug with precision in randTruncatedNormal().

**Comment by rwieruch** [comment]
Thank you @nkreeger Than I will close this for now. Just running into https://github.com/PAIR-code/deeplearnjs/issues/440 when upgrading to 0.3.14.
