### ISSUE TITLE
Incorrect broadcasting in NDArrayMath.multiply()

### ISSUE THREAD

**Issue by caisq** [PAIR-code/deeplearnjs#457]
The following code:
```javascript
const math = new deeplearn.NDArrayMathCPU();

math.scope(() => {
  const x = deeplearn.Array2D.new([2, 2], [[10, 20], [30, 40]]);
  const y = deeplearn.Array2D.new([2, 1], [[2], [4]]);
  const z = math.multiply(x, y);
  console.log(z.dataSync());
});
```

gives: `20,80,60,160`, instead it should be `20,40,120,160`. 

The result is correct if NDArrayMathGPU is used, though. It looks like that on CPU, the broadcasting incorrectly applies to rows, instead of columns.

**Comment by caisq** [comment]
cc @nsthorat

**Comment by caisq** [comment]
Thanks for the quick fix, @nsthorat !

**Comment by nsthorat** [comment]
No problem! We'll get this into the next release ASAP (once we fix the other fallout from the big global NDArrayMath change).
