### ISSUE TITLE
what do this JS can do in a project? 

### ISSUE THREAD

**Issue by LJ147** [PAIR-code/deeplearnjs#46]
Hello, I am very glad to see this amazing repo, which practices Deeplearning with JS. With respect, I'd like to know what's the point of this repo? This question might be a little rude , but I was just curious. 

So could you please give me some hints upon how to create some interesting projects or demos?

Will the training process be transferred to browser in the future?

**Comment by nsthorat** [comment]
Check out our blog post which explains our vision:

https://research.googleblog.com/2017/08/harness-power-of-machine-learning-in.html
