### ISSUE TITLE
Webpack and sourcemaps

### ISSUE THREAD

**Issue by QuantumInformation** [PAIR-code/deeplearnjs#476]
I'm not seeing any sourcemaps with models/squeezenet with the standard build options.

`    "build": "tsc --sourceMap false && browserify -g browserify-shim --standalone squeezenet index.ts -p [tsify] -o dist/bundle.js",`

What about gradually moving the builds to webpack which more people are familiar with?

![image](https://user-images.githubusercontent.com/216566/34387584-f6fc4918-eb26-11e7-8d8a-9f3a469b3d92.png)

![image](https://user-images.githubusercontent.com/216566/34387982-2dcfaf14-eb29-11e7-97b3-7fe4eb68ff36.png)

**Comment by ManrajGrover** [comment]
@QuantumInformation Sourcemaps are disabled in the command. If you want to enable them, change the build command to `tsc --sourceMap true && browserify -g browserify-shim --standalone squeezenet index.ts -p [tsify] -o dist/bundle.js`.

**Comment by QuantumInformation** [comment]
we should enable them in the demo I think
