### ISSUE TITLE
How to contribute (for beginners) ? 

### ISSUE THREAD

**Issue by umgupta** [PAIR-code/deeplearnjs#48]
Hi,
I wanted to start contributing to deeplearnjs. Is there a list of beginner bugs or enhancements etc., which I can work on?

**Comment by nsthorat** [comment]
Thanks for the interest!

What I'm going to do, in the next 2 weeks (sorry this is a little slow, maybe @dsmilkov can give a small task as a hold-over), is put together a page of tasks ranging from tiny to large that we would love to see as contributions, and that we would be glad to help you work through.

Would that be helpful? I will ping this issue when we're ready for that. (unfortunately, I'm on vacation for another week so my contributions are a little slowed-down)

**Comment by cseale** [comment]
I think that would be great, I'd love to get involved in this aswell

**Comment by umgupta** [comment]
@nsthorat Sounds good!! Watching this space for more :)

**Comment by bingo4508** [comment]
Looking forward to seeing the page of tasks with level! (I wish I can get familiar with the code base soon..)

**Comment by umgupta** [comment]
Still watching...

**Comment by andrii-maglovanyi** [comment]
hey guys! i'd like to participate as well, are there any updates on the topic?

**Comment by nsthorat** [comment]
Hi everyone!

Sorry about the delay - here is the link for help wanted issues. Checkout the "good first issue" sub label as well.
https://github.com/PAIR-code/deeplearnjs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

We're going to keep this updated. It's also linked from the README.md (the link will be on deeplearnjs.org homepage soon).

**Comment by dsmilkov** [comment]
We've also updated our [development section](https://github.com/PAIR-code/deeplearnjs/blob/master/README.md#development) in the README.md.

Closing this issue - feel free to reopen if you have any suggestions/feedback around the logistics of our setup of using labels in issues as "help wanted".
