### ISSUE TITLE
It would be nice if the hosted demos contained sourcemaps too

### ISSUE THREAD

**Issue by QuantumInformation** [PAIR-code/deeplearnjs#482]
http://deeplearnjs.org/demos/intro/

![image](https://user-images.githubusercontent.com/216566/34409334-279bd210-ebc1-11e7-8cb7-c320a19f6b0e.png)

**Comment by ManrajGrover** [comment]
@QuantumInformation Adding sourcemaps to the bundle increases bundle size and thus increases the time to load the page, which majority of the users wouldn't want. All of the demo code is open sourced here for viewing and using it locally. One thing we can do is add Github Code link to all demos which will make it easier to locate the source code.
