### ISSUE TITLE
Webpack example and existing Type Error in example code

### ISSUE THREAD

**Issue by QuantumInformation** [PAIR-code/deeplearnjs#491]
In this example here, I am getting a type error

https://github.com/PAIR-code/deeplearnjs/blob/master/docs/tutorials/ml_beginners.md#forward-mode-inference--numeric-computation

ERROR in [at-loader] ./src/index.ts:6:28
    TS2345: Argument of type 'number[]' is not assignable to parameter of type '[number, number]'.
  Property '0' is missing in type 'number[]'.

Here is a way to reproduce:

run `npm run build` here: https://github.com/QuantumInformation/deeplearnjs-playground

If you want I can also add this example to your examples

Also in the example, you can't do `console.log("result", await result.data());` unless is in an async function

Typescript error:

![image](https://user-images.githubusercontent.com/216566/34457875-c083772a-edb6-11e7-86eb-ca50f2582fb8.png)

**Comment by dsmilkov** [comment]
This is the TypeScript compiler being careful and wanting only an array of length 2.

To make the compiler happy change your line 5 from
`const matrixShape = [2, 3]`
to
`const matrixShape: [number, number] = [2, 3]`

This will tell the compiler that matrixShape is exactly of length 2, so you won't be allowed to assign more values to it, (e.g. `matrixShape[2] = ...` will result in compiler error)
