### ISSUE TITLE
NDArrayMathGPU deprecated but ENV.math not in API 

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#495]
Looks like 

`var math = new deeplearn.NDArrayMathGPU() `

has been deprecated and has been replaced with a predefined

`deeplearn.ENV.math`

**but I can't find anything about it in the API.**

Note: if you have the line
`dl = deeplearn `

somewhere in your code then the new line is 

`dl.ENV.math`

This change happened around version 0.3.14 

Note that most of the examples such as https://deeplearnjs.org/docs/tutorials/intro.html will still show 

NDArrayMathGPU()

The error warning is

`deeplearn.js:7622 new NDArrayMathGPU() is deprecated. Please use the global dl.ENV.math. In rare cases, to construct your own NDArrayMath that runs on GPU, use math = new NDArrayMath('webgl', safeMode); and make sure to set it as global: dl.ENV.setMath(math);`

Which seems sort of useful.

**Comment by dsmilkov** [comment]
Hi, we regenerated our website and our tutorials/demos to use `dl.ENV.math`. This is temporary and serves as migration path to the new simpler api that's coming.

**Comment by hpssjellis** [comment]
Thanks @dsmilkov
