### ISSUE TITLE
Request for greater_equal

### ISSUE THREAD

**Issue by michael-terry** [PAIR-code/deeplearnjs#506]
Akin to TF's greater_equal(): https://www.tensorflow.org/api_docs/python/tf/greater_equal

Other comparison operators may be useful: https://www.tensorflow.org/api_guides/python/control_flow_ops#Comparison_Operators

**Comment by ManrajGrover** [comment]
@dsmilkov I can take this one up.

**Comment by dsmilkov** [comment]
Awesome! Looking forward

**Comment by dsmilkov** [comment]
Fixed in #541  Thank you @ManrajGrover !
