### ISSUE TITLE
Firefox runs examples if the UA is spoofed to Chrome

### ISSUE THREAD

**Issue by jdashg** [PAIR-code/deeplearnjs#51]
Please feature-test, and don't UA sniff.

(Firefox Nightly on Windows)

**Comment by nsthorat** [comment]
We just recently fixed a major shader problem with Firefox where for loops has to be integer counters: https://github.com/PAIR-code/deeplearnjs/issues/11

The last issue is one of our demos (the NN-art) demo has a problem when polymer and material design lite are used together. We're going to fix this within the next few days (as you noticed, the library should work in Firefox now, though)!
