### ISSUE TITLE
Feature Request: NDArrayMath.reverse

### ISSUE THREAD

**Issue by caisq** [PAIR-code/deeplearnjs#512]
The ability to reverse an array along a given axis would be useful (e.g., for certain reversed RNNs)

The signature of the function can follow tensorflow's tf.reverse:
https://www.tensorflow.org/api_docs/python/tf/reverse

**Comment by haasdo95** [comment]
Any ideas on how to implement gradient for reverse...?

**Comment by dsmilkov** [comment]
Yup, simply calling reverse on `dy` should work. In the simplest case with an array with 2 elements `reverse([x1, x2], axis=0)`, you'll have:
`y1 = x2, y2 = x1`
`dx1 = dy2, dx2 = dy1`
which means `dx = reverse(dy, axis=0)`

**Comment by ManrajGrover** [comment]
This can now be closed with #535 being merged.
