### ISSUE TITLE
Using VSCode, clang-format and formatOnSave the editor modifies a lot of untouched code

### ISSUE THREAD

**Issue by chaosmail** [PAIR-code/deeplearnjs#515]
Hi guys,

I have VScode `v1.19.1`, Clang-Format Extension `v1.6.1`, TSLint Extension `v1.0.24` and Clang-Format `NPM version 1.0.41-b` installed (as stated in the Readme). When I open open the project in vscode (I use the untouched `.vscode/settings.json`), navigate to `src/math/math.ts` and hit save it automatically formats a lot of code. Here is on example:

before (Line 342):
```ts
const grad = (dy: NDArray, y: NDArray) => {
  return {x: () => dy.reshape(x.shape)};
};
```

after (Line 340):
```ts
const grad =
    (dy: NDArray, y: NDArray) => { return {x: () => dy.reshape(x.shape)}; };
```

Interestingly, after this auto-format tslint is complaining about the `return` keyword in the arrow function.

Has anyone seen a similar behavior before? Is there a setting or style definition that I am missing?

**Comment by dsmilkov** [comment]
You are right. The NPM version seems to be causing problems. I just reproduced the problem.

For now, until we figure out better solution, uninstall the npm clang-format and install the regular clang-format (version 6.0). If on Mac, and using homebrew, you can do `brew install clang-format`

Let me know if this helps.
