### ISSUE TITLE
Bug report: Property 'getFragmentShaderSource' does not exist 

### ISSUE THREAD

**Issue by kaihuchen** [PAIR-code/deeplearnjs#53]
Just pulled the very latest to refresh my deeplearnjs installation, and got the following error in the browser's console when trying to run the Model Builder. 

bundle.js:1 TypeScript error: src/math/webgl/addsubmuldiv_gpu.ts(34,23): Error TS2339: Property 'getFragmentShaderSource' does not exist on type 'typeof "src/math/webgl/binaryop_gpu"'.

Please advise.

**Comment by dsmilkov** [comment]
We removed `src/math/webgl/addsubmuldiv_gpu.ts` in a previous commit so you shouldn't have that file on your disk. I'm not sure how git pull handles removed files, that is, if it keeps your previous local files on disk.

**Comment by dsmilkov** [comment]
Also, did you sync to latest master by running `git pull`? Based on [this answer](https://stackoverflow.com/questions/7098586/git-pull-deleted-files), git pull should remove previously deleted files from your disk.

**Comment by kaihuchen** [comment]
I was using *git pull origin master* to sync. Just found that it won't auto-delete local files to match the master.

I created a fresh clone and all seem fine with the Model Builder now. Thanks!

On a separate note regarding the new LSTM demo, I found that the stated command (i.e., **./scripts/watch-demo demos/lstm/lstm.ts**) for starting the demo does not work, and I have to use **./scripts/watch-demo demos/lstm/lstm_inference.ts** instead.

**Comment by dsmilkov** [comment]
Nice catch! Fixed it.
