### ISSUE TITLE
create cpu local NDArray

### ISSUE THREAD

**Issue by pyu10055** [PAIR-code/deeplearnjs#533]
tensorflow stores parameter as tensor in their model file, naturally we will convert
that tensor into an NDArray, but that particular tensor is not used as input in Ops, 
it is just a param (for example axis for concat). 
The issue is now the NDArray is stored in GPU has to be downloaded the cpu in
order to retrieve the data, is it possible to specifically create an cpu local NDArray 
to avoid the above operation?

Thanks.

**Comment by dsmilkov** [comment]
I might be misunderstanding, so correct me if I'm not answering your question :)

In dljs, the params to our ops are often not `NDArray`s, but number|number[]|string. E.g. the signature of math.sum is:
`sum<...>(x: NDArray<D>, axis: number|number[] = null, keepDims = false): T`

which means when you parse TF params from the TF graph, you don't have to construct an `NDArray` to hold axis or keepDims. You can just use primitives.

**Comment by pyu10055** [comment]
You are right when the deeplearn.js params is also a param in the TF api, it will be store as part of the attr field in the Node. But there are cases when a deeplearn.js param is an input of the TF api.
The input will be translated to a node in the TF graph (most likely a constant node). 

On second thought, it is hard to differentiate the weight type of constant node from the param type of constant node, and the number of weight nodes is far greater than the param nodes. I sense there would not be much performance gain, if the count of param nodes is small.

Do you see any benefits of having the cpu only ndarray, or what is the difficulty of
having it? thanks.

**Comment by dsmilkov** [comment]
In a sense, we do have cpu-only `NDArray`s, but it's not by design that comes from the top, it's an implementation detail of our `WebGLBackend`, which decides to do lazy uploads, because uploads are expensive in that they could stall the gpu. In detail:

User-created `NDArray`s, e.g. `Scalar.new(6)` (not arrays that are result of math ops) are actually lazily uploaded to the GPU. E.g.
```ts
const a = Scalar.new(6); // Never uploads the gpu, data sits in cpu.
a.dataSync(); // Never causes the gpu to read pixels, since data is already on cpu.
math.square(a); // Now `a` gets uploaded to GPU, since webgl backend needs it.
a.dataSync(); // This causes gpu to read pixels, since `a`s data last lived in gpu.
```

So you will probably avoid perf issues, due to our lazy loading.

**Comment by pyu10055** [comment]
cool, in that case, my issues can be closed. thank for the explanation.
