### ISSUE TITLE
Implement test coverage for math.equal* methods.

### ISSUE THREAD

**Issue by nkreeger** [PAIR-code/deeplearnjs#538]
While implementing logical_or() - I noticed that the equal methods could use unit tests. Should be straight forward once I introduce a `logical_ops_test.ts` file soon.

**Comment by ManrajGrover** [comment]
@nkreeger We should also add tests for `math.notEqual*` methods. Should I create a separate issue for this?

Also, taking this one up.

**Comment by dsmilkov** [comment]
Closing this since tests for `equal/notEqual` already exist in `elementwise_arithmetic_test.ts`. See #542 regarding relocating these tests to avoid future confusion.
