### ISSUE TITLE
Looking for the graph.transpose API

### ISSUE THREAD

**Issue by bvahdat** [PAIR-code/deeplearnjs#545]
Given a vectorised implementation of the cost function for a linear hypothesis:
![screen shot 2018-01-13 at 16 32 33](https://user-images.githubusercontent.com/3122177/34907509-e72924f0-f87f-11e7-93c4-54fceea8c742.png)

I realised that `graph.transpose` API is missing for this purpose. Right now I've got it so far which is of course not correct yet:

```javascript
const j = graph.multiply(
    graph.subtract(graph.multiply(x, theta), y),
    graph.subtract(graph.multiply(x, theta), y));
```
Two pieces are still missing here:
- transposing the first matrix before multiplication
- the term 1/(2m)

Any idea how I can express those two terms?

**Comment by bvahdat** [comment]
I came up with the following which I'm not sure if it's correct (m is the size of the training set)

```javascript
const j = graph.reduceSum(graph.matmul(
  graph.reshape(graph.subtract(graph.matmul(x, theta), y), [1, m]),
  graph.subtract(graph.matmul(x, theta), y)));
```

**Comment by dsmilkov** [comment]
Hi,

With the [release of 0.5.0](https://github.com/PAIR-code/deeplearnjs/releases/tag/v0.5.0), we are deprecating the Graph API, in favor of the eager API, which allows for much easier development and debugging. 0.5.0 also has `dl.transpose` ([docs here](https://deeplearnjs.org/docs/api/index.html#dl.transpose)).

In eager mode, training consists of simply wrapping your computation (like `dl.floor`) in `optimizer.minimize()` call. See [this example](https://deeplearnjs.org/docs/api/index.html#dl.train.sgd) and [this tutorial](https://deeplearnjs.org/docs/tutorials/ml_beginners.html) for more details.
