### ISSUE TITLE
Still errors on tutorial pages

### ISSUE THREAD

**Issue by amadanmath** [PAIR-code/deeplearnjs#55]
Continuing on #22... `intro.ts` got added to give an executable equivalent to the tutorial page code, and it works nicely (thank you!), now I have a problem with the [Guide for ML beginners page](https://pair-code.github.io/deeplearnjs/docs/tutorials/ml_beginners.html).

I replicated the current beginner page code on [jsbin](https://jsbin.com/pexojojesu/edit?js,output) again, with the only change (that I can see) being namespacing; but I am getting `Uncaught Error: Placeholder node "y label" [] not present in feed dictionary.` from the `session.train(...)` call.

By analogy with the working code, I figured that the feed entries should be `[{tensor: x, data: xProvider}, {tensor: yLabel, data: yProvider}]` instead of `[{tensor: x, data: xProvider}, {tensor: y, data: yProvider}]`; but this resulted in `Uncaught Error: tensor 12 not in array map.`, so maybe I got it wrong. (What is "tensor 12" anyway?)

**Comment by nsthorat** [comment]
Ah I'm sorry, will fix this soon, I definitely should have actually ran these :)

As for your second comment, every Tensor gets a unique ID (the 'id' property). That error is telling us that we're trying to provide a Tensor that doesn't exist in the transitive dependencies of the Tensor we are evaluating. What you're saying is exactly right.

**Comment by jeff3dx** [comment]
Yah first thing I did was try to run the code on page "Guide for non-ML experts" and got the same error: "Uncaught Error: Placeholder node "y label" [] not present in feed dictionary."  A fix would be appreciated.

**Comment by nsthorat** [comment]
Working on this fix. There's a problem at head that is causing this error!

**Comment by nsthorat** [comment]
This should be fixed.
