### ISSUE TITLE
How to use math.floor in graph

### ISSUE THREAD

**Issue by hbhng** [PAIR-code/deeplearnjs#551]

**Comment by dsmilkov** [comment]
Hi,

With the [release of 0.5.0](https://github.com/PAIR-code/deeplearnjs/releases/tag/v0.5.0), we are deprecating the Graph API, in favor of the eager API, which allows for much easier development and debugging. In eager mode, training consists of simply wrapping your computation (like `dl.floor`) in `optimizer.minimize()` call. See [this example](https://deeplearnjs.org/docs/api/index.html#dl.train.sgd) and [this tutorial](https://deeplearnjs.org/docs/tutorials/ml_beginners.html) for more details.
