### ISSUE TITLE
Is layersSlider!.addEventListener right?

### ISSUE THREAD

**Issue by TaylorPzreal** [PAIR-code/deeplearnjs#59]
https://github.com/PAIR-code/deeplearnjs/blob/f3b71bc3d1995c70d53c538cff6100af94cd32f0/demos/homepage/index.ts#L106

**Comment by dsmilkov** [comment]
This is a valid operator in typescript, specifying that `layersSlider` is not null. However since we are not using `strictMode` for the typescript compiler anymore, we are removing all occurrences of the non-nullable operator in PR #60
