### ISSUE TITLE
Migrate optimizers to eager mode.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#592]
Now that we're going to be writing gradients with eager mode, optimizers should be moved to use the new API.

Optimizers should be moved to `./src/math/optimizers` as we migrate, and should simply implement "applyGradients".

SGD example: https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/optimizers/sgd_optimizer.ts#L38

For more information on eager, see this issue: https://github.com/PAIR-code/deeplearnjs/issues/561

**Comment by nsthorat** [comment]
@ManrajGrover if you're interested in picking up more, this would be a great one. You are doing an *amazing* job :)

**Comment by nsthorat** [comment]
I will take these on in 1 PR.

**Comment by nsthorat** [comment]
Removing from milestone as we will not ship with all optimizers (it took quite a bit of time for me to rewrite the optimizers from first principles, as well as unit tests).

I learned that RMSProp was not implemented correctly. @ManrajGrover, if you want to take on converting the last 3 optimizers, that would be immensely helpful (just make sure the existing implementations are correct, I will do the same during the review).

The principles I was taking:
- Mirror TF optimizer API exactly (all arguments / whether they are optional are identical)
- Simple unit tests. Whoever takes this on can copy the approach I took in https://github.com/PAIR-code/deeplearnjs/pull/668

RMSProp will need to be rewritten entirely.

**Comment by ManrajGrover** [comment]
@nsthorat Sure, I'll wait for #668 to merge before looking into the remaining optimizers. Thanks for pinging! :)

**Comment by nsthorat** [comment]
Merged! Let me know if you have any questions. Thanks for looking into this!

**Comment by ManrajGrover** [comment]
We can close this now :)

**Comment by dsmilkov** [comment]
Thanks @ManrajGrover for finishing the migration!
