### ISSUE TITLE
running  `yarn test --browsers=Chrome --grep='una'` without result

### ISSUE THREAD

**Issue by jaassoon** [PAIR-code/deeplearnjs#608]
Why running 
`yarn test --browsers=Chrome --grep='una'`
always raising
`Chrome 63.0.3239 (Mac OS X 10.13.2): Executed 0 of 5032 (skipped 5032) ERROR (20.526 secs / 0 secs)`

`yarn test --browsers=Chrome --grep='trans'` is OK
showing
`Chrome 63.0.3239 (Mac OS X 10.13.2): Executed 27 of 5032 (skipped 5005) SUCCESS (21.438 secs / 1.11 secs)` in console

**Comment by ManrajGrover** [comment]
@jaassoon It is because there were no test name could be found with keyword `'una'` in it, whereas there are test names which contain the keyword `'trans'` in them, hence they were executed.

**Comment by jaassoon** [comment]
But I found a file named src/math/unary_ops_test.ts
Does it match the keyword ‘una’?

**Comment by ManrajGrover** [comment]
@jaassoon The command looks for test names and not file names. I don't see a way to pass filename to karma. For now, if you wish to run specific tests, you should pass test names like `yarn test --browsers=Chrome --grep='ceil'`.

**Comment by nsthorat** [comment]
@ManrajGrover is correct, the karma doesn't know about the filenames, only what you use in "describe" and "it".

**Comment by jaassoon** [comment]
Ahh, I see.
Thank you for your answer @manrajgrover @nsthorat
