### ISSUE TITLE
Add dl.linspace and dl.arange.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#613]
We should add helper linspace and arange functions to generate numbers within a range.

**Comment by tafsiri** [comment]
@nsthorat Do you think there is any value in naming `arange` as `range` instead? I imagine the arange name in python is to make it distinct from the built in range function. My guess being arange -> 'array range', which doesn't have the same meaning/connotation in js (where arrays are the standard datastructure as opposed to lists).

**Comment by dsmilkov** [comment]
+1 to calling it just `range`. As you said, `arange` is a side-effect of `range` being already built-in in python :)
