### ISSUE TITLE
Calling asType on an RGBA packed integer texture does nothing.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#617]
```
const a = dl.fromPixels(image).asType('float32');
```

`a` will be of dtype 'float32', but when downloading will be a Uint32Array. This is because we simply no-op when casting an int => float texture on the GPU, but for packed integer textures we should be actually calling a shader to unpack the RGBA integer texture.

**Comment by dsmilkov** [comment]
After we added a `fromPixels` gpu shader that instantly unpacks pixels, `dl.fromPixels()` should return tensor of type `bool` that already holds unpacked data.

The fact that the instance is `UInt32Array` even after casting to `float32` is implementation detail, and shouldn't concern the user. In other words, `a.dataSync()[7]` will give you the 8th value, regardless of which flavor the TypedArray is.

**Comment by dsmilkov** [comment]
Fixed in #622. To be reopened if the instance of TypedArray matters to the user.
