### ISSUE TITLE
Change the signature of "gradients" to return a function.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#628]
Currently, "gradients()" takes a function and computes the output of that function with respect to some xs. We should be more like TensorFlow eager / autograd and return a function so it can be chained.

This is as simple as wrapping the body of the gradients function is a function closure.

See: https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/backends/backend_engine.ts#L130

**Comment by dsmilkov** [comment]
Fixed in #690
