### ISSUE TITLE
Tests failing on travis

### ISSUE THREAD

**Issue by tafsiri** [PAIR-code/deeplearnjs#630]
We seem to have some tests failing on travis. https://travis-ci.org/PAIR-code/deeplearnjs/builds/335849897 I think they were introduced in #627. @dsmilkov would you be able to take a look?

**Comment by nsthorat** [comment]
https://github.com/PAIR-code/deeplearnjs/pull/633

**Comment by nsthorat** [comment]
Ah, apologies. You are right, they were introduced here:

https://github.com/PAIR-code/deeplearnjs/pull/627

Specifically "clone" interacting with "set" now breaks:
https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/ndarray_test.ts#L74-L79

@dsmilkov can you send a fix?

**Comment by dsmilkov** [comment]
Yup, will remove `set` and `add` in NDArray. There is no point in keeping backwards compatibility with these 2 methods when we are making `NDArray`s immutable.

**Comment by dsmilkov** [comment]
Fixed in #625 (I did it in that PR since the fix was tiny, but I wanted to make sure Travis passes)
