### ISSUE TITLE
Convert tutorials to new API

### ISSUE THREAD

**Issue by tafsiri** [PAIR-code/deeplearnjs#649]

**Comment by tafsiri** [comment]
- [ ] Getting Started (on home page)
- [ ] Introduction
- [ ] Getting the best performance
- [ ] Guide for non-ML experts
- [ ] Example: Predicting Complementary Colors

**Comment by tafsiri** [comment]
I propose removing the current "Guide for non-ML experts" and folding its content into the introduction. Since graph mode is being deprecated and most of that page is about graph mode. I don't think we need it until we can re-write it completely. The portion I think we could move to the introduction is the description of tensors (mathematically/conceptually). 

Alternatively this page could be turned into an expanded training guide (since that is what it mainly focuses on—effectively that would be its rewrite). I'm working on an eager training section for the introduction, but maybe the content that is currently on this page can be used to expand on that.

Thoughts @dsmilkov @nsthorat?

**Comment by nsthorat** [comment]
Your plan sounds great to me. I would note that it would be really nice to have a guide from first principles at some point (assuming people don't know what a tensor is).

**Comment by QuantumInformation** [comment]
There is still a js file in the demos/Complementary Colors

**Comment by QuantumInformation** [comment]
What was the reason again for moving away from graph mode?

**Comment by nsthorat** [comment]
A few reasons, from user feedback we learned that Graph mode was confusing (a second API to learn), it doesn't provide advantages that it does in TensorFlow (graph optimizations), and eager mode is much much easier to debug (stack traces are sane, and not in graph execution code).
