### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by asross** [PAIR-code/deeplearnjs#675]
When I click on the documentation link in the README (or the main site), I get:

![image](https://user-images.githubusercontent.com/1022564/35976491-4af02bc2-0cae-11e8-960b-8a6a33eb7377.png)

**Comment by dsmilkov** [comment]
Thanks! API is back up. Just to give you a heads up, we are working on releasing 0.5.0 with revamped simplified docs and much simpler API. You can follow this on the [milestone page](https://github.com/PAIR-code/deeplearnjs/milestone/1)
