### ISSUE TITLE
Use dl.variable in optimizers.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#678]
It would be nice to hold optimizer caches / accumulations as dl.variables so they we can use "assign" and also serialize them.

Another thing to think about - do we want to make it easy to recognize training variables with another bit to "dl.variable"?

**Comment by dsmilkov** [comment]
Any ideas what the benefit wil be of having a special bit for training-related variables? Is `trainable: false` not sufficient?

**Comment by dsmilkov** [comment]
Thanks! Makes sense. Still unclear if dl.js API should be designed for serialization (maybe we leave it to higher-level layers), but we should def revisit later.
