### ISSUE TITLE
Variable.assign should not dispose input tensor.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#681]
Right now when you call "assign" on a variable with an input tensor, we dispose that input tensor.

This makes sense if you are setting up weights, but uses of variables in complex situations like optimizers makes this quite awkward.

```
const newVariable = tidy(() => {
  const newAccumulation = this.m.mul(accumulation).add(gradient);
  this.accumulations[variableName].assign(newAccumulation);
        
  // The next line throws an error because newAccumulation has been disposed.
  return this.c.mul(newAccumulation).add(value);
});
```

Assign should probably not dispose the input tensor.

**Comment by dsmilkov** [comment]
@nsthorat This is fixed right? Feel free to close upon confirmation.

**Comment by nsthorat** [comment]
Correct, this is fixed.
