### ISSUE TITLE
Any plan to support weights quantization?

### ISSUE THREAD

**Issue by dikatok** [PAIR-code/deeplearnjs#694]
Thanks for the great project

I see that there is currently a separate project about converting frozen model but do we have any plan to support weights quantization during checkpoint convertion? Or it's not necessary since we can reuse quantization in tensorflow toco? Especially when the frozen model support is ready.

**Comment by dsmilkov** [comment]
@pyu10055 and @nkreeger for more details.

**Comment by pyu10055** [comment]
The plan is to use [grappler](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/grappler) instead of TOCO for graph optimization,  weight quantization will not be in the initial release. It will be high in our radar, since it is crucial for reducing the weight file size.

**Comment by dikatok** [comment]
Wow, have never heard of grappler module before. That sounds like a good plan, thanks!
