### ISSUE TITLE
Documentation not in sync with npm version

### ISSUE THREAD

**Issue by amelon** [PAIR-code/deeplearnjs#695]
Hello,

current doc and api is not accurate with npm published version.

eg: tidy does not exist in 0.4.2 as SymbolicTensor.

Could you please publish a new npm version with your last code version?

It would be very helpful.
Thanks

**Comment by nsthorat** [comment]
We will be publishing a new version, 0.5.0, on Wednesday with a brand new API reference page that has been more manually curated.

**Comment by dsmilkov** [comment]
Yeah, apologies for the temporary out of sync. You can follow the progress for 0.5.0 here: https://github.com/PAIR-code/deeplearnjs/milestone/1

**Comment by amelon** [comment]
thanks for info and good news :)

**Comment by dsmilkov** [comment]
We released [0.5.0](https://github.com/PAIR-code/deeplearnjs/releases/tag/v0.5.0) today! Feel free to reopen if you run into issues documentation issues.
