### ISSUE TITLE
Bring back default jasmine timeout limit for some dl.data tests

### ISSUE THREAD

**Issue by dsmilkov** [PAIR-code/deeplearnjs#704]
See #701 for context

**Comment by dsmilkov** [comment]
Also it would be nice if we can make the test running time much shorter - ideally as short as possible

**Comment by nsthorat** [comment]
+1, can you submit that change that yells when tests go over 500ms?

**Comment by davidsoergel** [comment]
I'm looking into the issue with my tests (briefly, ChainedStream seems to be slow in general, maybe due to long promise chains).  But also, +1 to having a warning for tests that are slower than desired but not too slow to fail outright.

**Comment by dsmilkov** [comment]
Adding the warning in PR https://reviewable.io/reviews/pair-code/deeplearnjs/708/karma.conf.js
We also have a few slow tests in ops - speeding up should be easy.

**Comment by dsmilkov** [comment]
FYI, that PR produced a new log where all slow tests are logged. Search for "SLOW" in https://api.travis-ci.org/v3/job/341233182/log.txt

**Comment by davidsoergel** [comment]
Nice, so all of my tests are slow, not just the ones implicated before :O
