### ISSUE TITLE
Tutorial out of date

### ISSUE THREAD

**Issue by OliverLonghi** [PAIR-code/deeplearnjs#726]
I´m trying to follow [this](https://deeplearnjs.org/docs/tutorials/intro.html) tutorial using [this](https://github.com/PAIR-code/deeplearnjs/tree/master/starter/typescript) starter project but it is not compiling this snippet taken from the tutorial:

```
import * as dl from 'deeplearn';
...
const a = dl.Array2D.new([2, 2], [1.0, 2.0, 3.0, 4.0]);
const b = dl.Array2D.new([2, 2], [0.0, 2.0, 4.0, 6.0]);
const average = c.sub(d); // ...
```

Error is: 
`[ts] Property 'sub' does not exists on type 'Array2D<"float32" | "int32" | "bool">'.`

**Comment by OliverLonghi** [comment]
Found another snippet not compiling on the same tutorial.

![image](https://user-images.githubusercontent.com/22771958/36258359-75c3564c-1241-11e8-93a6-9a6e17decb3e.png)

**Comment by dsmilkov** [comment]
Hi @OliverLonghi 

We just updated the tutorials and the docs and are about to release 0.5.0 (whose API matches those docs) later today. Stay tuned!

**Comment by TGotwig** [comment]
Hey there 🤗
In your "Guide for non-ML experts" tutorial,
you are using the matrixTimesVector function,
but javascripts says to me

> dl.matrixTimesVector is not a function

was it renamed or something?

**Comment by TGotwig** [comment]
Nope, from https://deeplearnjs.org/docs/tutorials/ml_beginners.html
Okay looking forward 🤗

**Comment by nsthorat** [comment]
0.5.0 has been released: https://github.com/PAIR-code/deeplearnjs/releases/tag/v0.5.0
