### ISSUE TITLE
Change how we do shader program cache keys to be less vulnerable to missing params in the cache key.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#75]
Right now, if you miss adding a params for the shader program cache key, two programs that have different source code may get cached to the same WebGLProgram.

A couple solutions:
1) Cache based on the entire program source. This is durable, but may be expensive.
2) Make every GPGPUProgram take a Params object as the only item in the constructor. Parse out elements from Params to build the shader source, and automatically generate the key from the Params object.

**Comment by reiinakano** [comment]
May be a stupid suggestion but.. how about caching based on the entire program source's hash?

**Comment by nsthorat** [comment]
Yeah this is a good idea, I think that's what JavaScript does under the covers if you have a large string key, but I'm not 100% sure I'll have to do a little research.

The question is how expensive making that hash is (either by the natural JavaScript hashing, or explicit hashing), since we would have to assemble & hash the program source every time you call a math command. Right now, the lookup is super cheap because we try to limit what we use as the cache key.
