### ISSUE TITLE
Update Demos to Eager API

### ISSUE THREAD

**Issue by abrad1212** [PAIR-code/deeplearnjs#766]
Are the demos gonna be updated to the Eager API, specifically the Model Builder?

This could be extremely helpful when trying to learn how all the layers work.

**Comment by tafsiri** [comment]
@abrad1212 as we have time we will be upgrading the demos to use eager. Especially since we intend to remove the graph api completely.

**Comment by tafsiri** [comment]
will be tracked in #651

**Comment by abrad1212** [comment]
@tafsiri Thanks for the info :). 

I'm really having trouble getting a convolutional network built with the Eager API, are there any resources/tutorials you could recommend?
