### ISSUE TITLE
Convolutional Neural Network examples

### ISSUE THREAD

**Issue by abrad1212** [PAIR-code/deeplearnjs#774]
I'm really having trouble getting a convolutional network built with the Eager API, are there any resources/tutorials that anybody could recommend?

Would constructing a CNN be similar to [this TensorFlow](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3_NeuralNetworks/convolutional_network.py) example?

**Comment by tafsiri** [comment]
@abrad1212 I just committed a change to https://github.com/PAIR-code/deeplearnjs/blob/master/demos/mnist_eager/model.ts that implements an mnist detector with a  convolutional network. Hope that helps show what a conv network looks like.

It's in typescript, to convert to typescript you would just remove the type annotations. But I will be working on posting a JS version of this and will update here once I do.

**Comment by abrad1212** [comment]
@tafsiri Thanks!
