### ISSUE TITLE
If adding dl.browser.image Issue #751 why not add dl.browser.data like in the minst_eager model

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#777]
I noticed you want to add the core utility dl.browser.image at https://github.com/PAIR-code/deeplearnjs/issues/751

Would be great if you could also add an extendable class like what was used in the [mnsit_eager demo](https://github.com/PAIR-code/deeplearnjs/tree/42d1fe186a4b91edae2b14c3d9bb4785c862a3c4/demos/mnist_eager) the MnistData class code at
https://github.com/PAIR-code/deeplearnjs/blob/42d1fe186a4b91edae2b14c3d9bb4785c862a3c4/demos/mnist_eager/data.ts#L25

The code could be made more general for adding many typical datasets like in the [Wiki List of Datasets](https://en.wikipedia.org/wiki/List_of_datasets_for_machine_learning_research)

The main code needed would be similar to the "load" function at

https://github.com/PAIR-code/deeplearnjs/blob/42d1fe186a4b91edae2b14c3d9bb4785c862a3c4/demos/mnist_eager/data.ts#L71-L82

Still use  JSON information to pass the various properties needed by the class.
https://github.com/PAIR-code/deeplearnjs/blob/42d1fe186a4b91edae2b14c3d9bb4785c862a3c4/demos/mnist_eager/data.ts#L5-L23

This load ability would allow deeplearnjs to be much easier to load multiple dataset much like http://scikit-learn.org/stable/ makes loading datasets easier.

The user would still have to write the trainData and testData methods but at least the dataset would be easier to load.

**Comment by nsthorat** [comment]
Hi @hpssjellis,

MnistData is going to get replaced with a dataset API that extends to many more datasets than what we have in MNIST Eager. All of the old dataset code is going to go away (XHRDataset, etc). The data.ts in mnist_eager was designed to potentially be used as the API to datasets, but it's not 100% clear yet.

Right now, we have the beginnings here (thanks @davidsoergel), but it is not ready yet: https://github.com/PAIR-code/deeplearnjs/tree/master/src/contrib/data

Stay tuned :)

**Comment by hpssjellis** [comment]
Looks good @nsthorat and @davidsoergel . This issue can be closed. Looking forward to testing it in pure Javascript.
