### ISSUE TITLE
Bignumber & Float64 support

### ISSUE THREAD

**Issue by lab4quant** [PAIR-code/deeplearnjs#778]
Hello, 
[Float64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array) is out in `ES2017`, will high accuracy big number be supported?

For now it would require 3rd party library to use big number, e.g. decimal.js, math.js etc

It would be great if `deeplearn` could support bignumber calculation, thanks!

**Comment by linkerlin** [comment]
Float64 is slower;
int8 is better for most ANN.

**Comment by nsthorat** [comment]
I don't think we'll use 64 bit floats at any point in the near future. WebGL only supports 32 bit floating point textures across the board, and we do very little CPU computation.

In terms of prioritization, working with reduced precision is actually higher on our list for memory / wall time concerns :)

**Comment by lab4quant** [comment]
understood, thanks for the update!
