### ISSUE TITLE
Awesome new API, needs, search and link to older versions

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#781]
Really impressed with the new API. It is however missing 2 basic items

https://deeplearnjs.org/docs/api/index.html

1. A search text box, ctrl F works fine in the browser but most people would probably like a search entry area

2. A link to the old API for people still using NDArray's

P.S. The new RUN buttons are a nice touch. Looks like a lot of work went into the API

Just found out that the two run buttons for "dl.minimum(a, b)" don't work, all the others are fine.

**Comment by tafsiri** [comment]
Thanks for the comments @hpssjellis. In case you happen to need the docs for the old version right now you can see them at https://storage.googleapis.com/dljs-docs/api042/globals.html I'll look into getting a link somewhere more visible.

**Comment by tafsiri** [comment]
And thanks for pointing out the typo in the minimum docs.

**Comment by hpssjellis** [comment]
Was very surprised that with version 0.5.0 my old code still worked. (I just finished a beginner video series about a week ago) the website is at https://hpssjellis.github.io/deeplearnjs-javascript-examples/    and all the examples that used version 0.4.2 still work with deeplearnjs version 0.5.0, but many classses are not in the API.  Is there a deprecation timeline?

P.S. @tafsiri Are you the new guy on the deeplearnjs project?

**Comment by dsmilkov** [comment]
I'm glad your old code worked! Backwards-compatibility for es6 users was the goal. There is a deprecation plan; see section "What’s deprecated" in the [0.5.0 release notes](https://github.com/PAIR-code/deeplearnjs/releases/tag/v0.5.0).

**Comment by hpssjellis** [comment]
Thanks. Here are a few quotes from the 0.5.0 release notes relevant to this thread

> **We will be removing the NDArrayMath in 0.6.****


> **Finally, welcome to the team @tafsiri, @nkreeger and @pyu10055!**

I thought there was only going to be one new team member. Very happy to find out that there are 3.

**Comment by tafsiri** [comment]
@hpssjellis Yep i'm one of the new ones! Very glad to hear that everything still worked with 0.5, we hope this version can provide a smooth transition point and allow people to update their code without major breakage. 

Cool video series!

**Comment by hpssjellis** [comment]
> Cool video series!

Thanks @tafsiri , I want to do a youtube video playlist for [Machine Learning](https://www.youtube.com/watch?v=7Vnn7hNk120&list=PL57Dnr1H_egukaDgFqwEnDVStd7Jktg1E) like what I have done for [Robotics ](https://www.youtube.com/watch?v=bOPonnhGOUg&list=PL57Dnr1H_egsL0r4RXPA4PY2yZhOJk5Nr)

It took a few years to classroom test the robotics stuff, may take a bit longer to learn and classroom test Machine Learning.

I think this issue can be closed.
