### ISSUE TITLE
Add CI testing

### ISSUE THREAD

**Issue by dsmilkov** [PAIR-code/deeplearnjs#8]
Travis CI is easy to integrate with GitHub. The only complication is that we depend on webgl, and headless browsers don't have that. Some people have claimed success with using https://github.com/stackgl/headless-gl and travis.

**Comment by dsmilkov** [comment]
Turns out headless-gl doesn't support `OES_texture_float`. In order to unblock travis CI integration, we need to use textures with `gl.UNSIGNED_BYTE` data type. This issue is tracked at #19.

**Comment by nsthorat** [comment]
Does it not support the extension at all? If not, then we're out of luck entirely. The gl.UNSIGNED_BYTE trick is just because gl.readPixels for floating point textures is not available. We might want to abstract gl_FragColor and do integer packing in testing mode so we can get this working.
