### ISSUE TITLE
Using OpenPose model in deeplearn

### ISSUE THREAD

**Issue by lisajamhoury** [PAIR-code/deeplearnjs#800]
Hi There, I'm working with the ml5 team at ITP and we have recently been looking into [OpenPose ](https://github.com/CMU-Perceptual-Computing-Lab/openpose) for real-time body detection in the browser. The trained model is a caffe model of about 200mb. Is it possible to pull this into deeplearn? Thanks!

**Comment by tafsiri** [comment]
Hi @lisajamhoury, we don't have explicit support for loading or importing Caffe models, so you would likely have to reimplement the model architecture, and then import the weights manually.

We are broadly interested in making it easier to import existing models so future releases may make this easier, but for now it would need something like what I described above.
