### ISSUE TITLE
Track down Scalar texture leak in the model builder.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#81]
Model builder has a texture leak at head (looks like it's part of the graph runner metrics evaluation).

Let's track this down.

**Comment by nsthorat** [comment]
I believe this was caused by not disposing of the momentum scalar in the momentumOptimizer, caused by
#62 

@mnottheone if you feel up for it, could you move the momentum scalar to the constructor?

**Comment by mnottheone** [comment]
Thanks for figuring it out. I will make the changes. Here, I have few doubts.
- We are not disposing learningRate in sgd_optimizer.ts , won't it also lead to texture leak. 
- How did it you figured out that there is texture leak and tracked it down? To make sure I won't repeat this in future, I think I should learn this.

**Comment by nsthorat** [comment]
Yes, you're totally right. If we don't dispose this.c before resetting it (when batch size changes), this is a texture leak.

As for tracking down texture leaks, we're trying to think of a better way to track them down, but right now set a break point here (after several loops of training have happened):
https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/webgl/texture_manager.ts#L46

**Comment by dsmilkov** [comment]
@nsthorat, is this issue still relevant?

**Comment by nsthorat** [comment]
Nope.
