### ISSUE TITLE
locToIndex and indexToLoc missing from API

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#816]
This seems to work, but not in API. 

`console.log(dl.tensor([1.1,2.2,3.3,4.4],[2,2]).indexToLoc(3))
console.log(dl.tensor([1.1,2.2,3.3,4.4],[2,2]).locToIndex([1,1]))`

**Comment by dsmilkov** [comment]
Hi @hpssjellis 

Curious in what scenarios you need these methods? They are not documented and we removed them in `0.6.0-alpha` (pre-release).

We moved those methods to the [`TensorBuffer`](https://deeplearnjs.org/docs/api/index.html#class:dl.TensorBuffer) class (we will add documentation for them). See [`dl.buffer()`](https://deeplearnjs.org/docs/api/index.html#dl.buffer) for creating new buffers.

The idea is that buffers are read/write and tensors are read-only. When you populate a buffer and are ready to get a tensor, call `buffer.toTensor()`. The idea is similar to String vs StringBuffer. Does that make sense?

**Comment by hpssjellis** [comment]
@dsmilkov  

> Curious in what scenarios you need these methods?

Mainly for html presentation of the data.

If you run my [htmlPrint](https://hpssjellis.github.io/deeplearnjs-javascript-examples/Unordered-javascript-examples/deeplearnjs-examples/htmlprint/htmlPrint.html) demo click the buttons and then  mouseOver the chart it gives the location of each element.


![indextoloc](https://user-images.githubusercontent.com/5605614/37221529-3257c592-237f-11e8-8b21-a7e1c6b52765.png)

Unlike the index, the location can sometimes make it easier to iterate through an array (tensor) using a "for loop".

Looks like you have got most of my issues covered with `tensor3d.get(i, j, k)`and I saw TensorBuffer but did not really understand it, however this makes perfect sense

> The idea is that buffers are read/write and tensors are read-only.


P.S. If you do use an indexToLoc command I would make the suggestion that the location match the Tensor definitions and possible cell locations in a different way than the present system. My suggestion is in the following diagram.

![better-location02](https://user-images.githubusercontent.com/5605614/37223208-a96598e4-2384-11e8-80cc-5f00d2e57af8.png)


Thanks for the very clear explanations.
