### ISSUE TITLE
Type to use with the tidy function

### ISSUE THREAD

**Issue by QuantumInformation** [PAIR-code/deeplearnjs#836]
I'm trying the performance tutorial with typescript, any ideas how to fix:

TS2345: Argument of type '(keep: any) => void' is not assignable to parameter of type 'string | ScopeFn<void>'.
  Type '(keep: any) => void' is not assignable to type 'ScopeFn<void>'.

<img width="788" alt="screen shot 2018-03-09 at 16 02 58" src="https://user-images.githubusercontent.com/216566/37221160-dec414ac-23c0-11e8-9c91-7639e44b1ced.png">

**Comment by nsthorat** [comment]
Instead of using `keep` as the argument in tidy, you can call `dl.keep()` directly.

**Comment by dsmilkov** [comment]
Yes, since 0.5.0 `dl.tidy()` takes a function with no arguments. that is
```js
dl.tidy(() => {
  dl.keep(something);
});
```

**Comment by QuantumInformation** [comment]
Thx for clarification
