### ISSUE TITLE
How do I extend the Tensor class while using dl.tensor to initialize it?

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#838]
@dsmilkov Thanks for solving 

**" Possible bug in Version 0.5.1 .print not working for Tensor Class [#822](https://github.com/PAIR-code/deeplearnjs/issues/822) "**

but it brings up another issue that I have:

When I extend the Tensor class, how do I construct it using dl.tensor  ?

See working demo at [https://hpssjellis.github.io/deeplearnjs-javascript-examples/active-work/basic02.html](https://hpssjellis.github.io/deeplearnjs-javascript-examples/active-work/basic02.html)

Here is my class definition:

```
<script src="https://unpkg.com/deeplearn"> </script> 

<script>
        
class myTensor extends dl.Tensor {
    async myMethod()  {
       const myOutput =  await this.data()
       alert(myOutput)
    }  
}      
    
</script>

<input type="button" value="Extend Tensor Class" onclick="{   
   const myWeights  = new myTensor([2,2],'float32',[1,2,3,4]);
   myWeights.myMethod()
}"><br> 

```

Tried several ideas, such as extending dl.tensor but still getting errors. Any suggestions.

**Comment by tafsiri** [comment]
I think you would effectively have to overwrite dl.tensor to call the constructor of your new class (but still correctly construct it). In the process that code would effectively become incompatible with the library though. I also say we generally avoid using `new` in the code we write that uses the library.

Generally I think I'd suggest just having a function that takes a tensor and does some operation on it. 

The classical way to do this would be to add methods to the prototype of dl.Tensor (or to just the specific tensor object you want to augment). However you would still need to be careful to not overwrite an existing method, or that a new release of the library doesn't add or use a method with the same name. 

That approach however modifies all tensors though, so what I would suggest is that in your constructor, construct a tensor in the regular way and then adds a function to each object it creates and then returns that. 

Something like the following (psuedocode)

```
class myTensor extends dl.Tensor {
     constructor(take the args) {
        const t = dl.tensor(pass the arguments)

        t.myMethod = function() {
          const myOutput =  await this.data()
          alert(myOutput)
       }

       // add more methods here

       return t;
     }
} 
``` 

You can actually just skip the class above and just make a function myTensor that does this.

**Comment by hpssjellis** [comment]
Thanks @tafsiri . I will see what I can do. I understand your psuedocode and will try it out. 

If anyone else has a working version feel free to add your code.

I hope extending a Tensor class does not break compatibility with Deeplearnjs.

**Comment by hpssjellis** [comment]
@tafsiri 

Your brilliant. That solved both issues. Here is a [demo ](https://hpssjellis.github.io/deeplearnjs-javascript-examples/active-work/basic03.html)


Here is the code:

```
<script src="https://unpkg.com/deeplearn"> </script> 

<script>
        
class myTensor extends dl.Tensor {
    constructor(a,b) {
        const t = dl.tensor(a,b)
   
        t.myMethod = async function() {
            const myOutput =  await this.data()
            alert(myOutput)
        }

       // add more methods here

       return t;
      } // end constructor
}       // end extended class

</script>

Click button with console open. Alert presents data from the extended tensor<br>

<input type="button" value="Extended Tensor Class with dl.tensor constructor" onclick="{   
   const myExtended  = new myTensor([1, 2.97, 3, 4], [2, 2]);
   myExtended.myMethod()
   myExtended.print('verbose')
}"><br>


```




Thank you very much for solving that so fast. I just had to add "async" and "await" to your psuedocode, and it does need "new" when making the class. Close this issue if you wish, but others may want to know how to solve the problem.

**Comment by tafsiri** [comment]
Glad it worked @hpssjellis. A couple of more suggestions depending on where you want to take this.

1. You could remove the `extends dl.Tensor` on your class with no ill effect. The return value from the constructor is a tensor anyway and will work as you expect, so it would look like
 
```js
class myTensor extends dl.Tensor {
    constructor(a,b) {
        const t = dl.tensor(a,b)
   
        t.myMethod = async function() {
            const myOutput =  await this.data()
            alert(myOutput)
        }

       // add more methods here

       return t;
      } // end constructor
}       // end extended class
```

2. You could skip the overhead of a class and a `new` operator all together by turning the constructor into a regular function like so:

```js
function myTensor(a,b) {
  const t = dl.tensor(a,b)

  t.myMethod = async function() {
      const myOutput =  await this.data()
      alert(myOutput)
  }

 // add more methods here
 return t;
} 

const augmentedTensor = myTensor([1, 2.97, 3, 4], [2, 2]);
augmentedTensor.myMethod();
```

**Comment by hpssjellis** [comment]
Thanks @tafsiri I put all 3 working versions in a github folder

[https://github.com/hpssjellis/deeplearnjs-javascript-examples/tree/78d51924c0a9f9ce8292bb5a2ae6fd3a59224a04/Unordered-javascript-examples/deeplearnjs-examples/class-extend](https://github.com/hpssjellis/deeplearnjs-javascript-examples/tree/78d51924c0a9f9ce8292bb5a2ae6fd3a59224a04/Unordered-javascript-examples/deeplearnjs-examples/class-extend)
