### ISSUE TITLE
best way to write a bias_add operation?

### ISSUE THREAD

**Issue by seranus** [PAIR-code/deeplearnjs#866]
I don't see bias_add in the documentation and adding higher shape with a 1d tensor doesn't work, 

What's the best way to do the operation?

**Comment by physicsrob** [comment]
dl.add(a,b) should be sufficient, unless I'm missing something?  dl.add supports broadcasting.
```
const a = dl.tensor1d([10, 20, 30, 40]);
const b = dl.tensor2d([[5,5,5,5],[5,5,5,5]])
a.add(b).print();
```
