### ISSUE TITLE
Graph MaxPool calculates wrong shape when zeroPad is omitted

### ISSUE THREAD

**Issue by dnnsthnnr** [PAIR-code/deeplearnjs#96]
Hello,

In my graph I got a convolutional layer which has an output shape of (28, 28, 32) when I use a maxPool layer with stride 2, fieldSize 2 and omit the zeroPad argument (since it's optional) it calculates an output shape of (28, 28, 32), which is incorrect. But if I set the zeroPad argument to 0 it calculates the correct output shape of (14, 14, 32). In my opinion, the optional zeroPad argument should be treated as same as setting it to 0.

I am using the version 0.1.2.

**Comment by nsthorat** [comment]
@dsmilkov is working on padding related convolutional changes

**Comment by nsthorat** [comment]
We are now identical to the TF API.
