### ISSUE TITLE
Organize the code base a little better.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#97]
We have lots of files in the root of src/, we should try to make the directory structure a little more sane as the code base grows.

**Comment by ivikash** [comment]
Any plans/ideas on this?

**Comment by innodeta** [comment]
I would propose a structure like

math/
    ops/
graph/
dataset/
optimizer/
utils/

**Comment by dsmilkov** [comment]
We re-organized the code few weeks ago. Fixed in #133.
